// Vampire Crawlers 卡牌数据
// 数据来源：https://vampire.survivors.wiki/w/Crawlers

const CARDS = [
  // ═══════════════════════════════════════
  // 攻击类卡牌（39张）
  // ═══════════════════════════════════════

  // -- 0费 --
  { id: "bone", name: "骨头", category: "攻击", rarity: "common", image: "images/bone.png", description: "对多个敌人造成3点伤害。", stats: { mana: 0, attack: 3, special: "多目标" }, craftable: false },
  { id: "knife", name: "飞刀", category: "攻击", rarity: "common", image: "images/knife.png", description: "造成40点伤害。暴击。", stats: { mana: 0, attack: 40, special: "暴击" }, craftable: false },
  { id: "magic_wand", name: "强能魔杖", category: "攻击", rarity: "common", image: "images/magic_wand.png", description: "造成30点伤害。优先攻击攻击者。", stats: { mana: 0, attack: 30, special: "优先攻击者" }, craftable: false },
  { id: "whip", name: "神鞭", category: "攻击", rarity: "common", image: "images/whip.png", description: "对多个敌人造成8点伤害。", stats: { mana: 0, attack: 8, special: "多目标" }, craftable: false },

  // -- 1费 --
  { id: "cherry_bomb", name: "樱桃炸弹", category: "攻击", rarity: "common", image: "images/cherry_bomb.png", description: "造成18点伤害。有几率爆炸。", stats: { mana: 1, attack: 18, special: "爆炸" }, craftable: false },
  { id: "fire_wand", name: "火焰魔杖", category: "攻击", rarity: "common", image: "images/fire_wand.png", description: "造成45点伤害。", stats: { mana: 1, attack: 45 }, craftable: false },
  { id: "garlic", name: "大蒜", category: "攻击", rarity: "common", image: "images/garlic.png", description: "对前排造成10点伤害。缴械。", stats: { mana: 1, attack: 10, special: "缴械" }, craftable: false },
  { id: "gatti_amari", name: "彪悍猫", category: "攻击", rarity: "common", image: "images/gatti_amari.png", description: "造成25点伤害。有几率引发混战。", stats: { mana: 1, attack: 25, special: "混战" }, craftable: false },
  { id: "gorgeous_moon", name: "华月纹章", category: "攻击", rarity: "common", image: "images/gorgeous_moon.png", description: "抹除1个敌人。月升。", stats: { mana: 1, attack: 999, special: "抹除" }, craftable: true },
  { id: "king_bible", name: "国王圣经", category: "攻击", rarity: "common", image: "images/king_bible.png", description: "造成40点伤害，有几率击退。", stats: { mana: 1, attack: 40, special: "击退" }, craftable: false },
  { id: "runetracer", name: "痕印石", category: "攻击", rarity: "common", image: "images/runetracer.png", description: "造成15点伤害。弹射造成更多伤害。", stats: { mana: 1, attack: 15, special: "弹射" }, craftable: false },

  // -- 2费 --
  { id: "axe", name: "斧头", category: "攻击", rarity: "rare", image: "images/axe.png", description: "对多个敌人造成45点伤害，有几率击退。", stats: { mana: 2, attack: 45, special: "多目标/击退" }, craftable: false },
  { id: "bloody_tear", name: "血笞", category: "攻击", rarity: "rare", image: "images/bloody_tear.png", description: "对多个敌人造成40点伤害。暴击时：回复3点生命。", stats: { mana: 2, attack: 40, special: "多目标/暴击回血" }, craftable: true },
  { id: "carrello", name: "推车", category: "攻击", rarity: "rare", image: "images/carrello.png", description: "对多个敌人造成45点伤害，有几率击退。", stats: { mana: 2, attack: 45, special: "多目标/击退" }, craftable: false },
  { id: "celestial_dusting", name: "英华天落", category: "攻击", rarity: "rare", image: "images/celestial_dusting.png", description: "造成35点伤害。小爱心。", stats: { mana: 2, attack: 35, special: "小爱心" }, craftable: false },
  { id: "cross", name: "十字飞镖", category: "攻击", rarity: "rare", image: "images/cross.png", description: "造成80点伤害。", stats: { mana: 2, attack: 80 }, craftable: false },
  { id: "eight_the_sparrow", name: "麻雀小八", category: "攻击", rarity: "rare", image: "images/eight_the_sparrow.png", description: "造成35点伤害。", stats: { mana: 2, attack: 35 }, craftable: false },
  { id: "holy_wand", name: "神授魔杖", category: "攻击", rarity: "rare", image: "images/holy_wand.png", description: "造成150点伤害。优先攻击攻击者。", stats: { mana: 2, attack: 150, special: "优先攻击者" }, craftable: true },
  { id: "lightning_ring", name: "闪电戒指", category: "攻击", rarity: "rare", image: "images/lightning_ring.png", description: "造成125点伤害。", stats: { mana: 2, attack: 125 }, craftable: false },
  { id: "unholy_vespers", name: "渎神祷书", category: "攻击", rarity: "rare", image: "images/unholy_vespers.png", description: "造成120点伤害，有几率击退。", stats: { mana: 2, attack: 120, special: "击退" }, craftable: true },
  { id: "valkyrie_turner", name: "瓦尔基里喷枪", category: "攻击", rarity: "rare", image: "images/valkyrie_turner.png", description: "对前排造成25点伤害。女武神的炼狱。", stats: { mana: 2, attack: 25, special: "女武神炼狱" }, craftable: true },
  { id: "vicious_hunger", name: "饕恶魔眼", category: "攻击", rarity: "rare", image: "images/vicious_hunger.png", description: "造成100点伤害。可将敌人变为金币。", stats: { mana: 2, attack: 100, special: "变金币" }, craftable: true },

  // -- 3费 --
  { id: "death_spiral", name: "死亡旋风", category: "攻击", rarity: "epic", image: "images/death_spiral.png", description: "对前排造成160点伤害。暴击。", stats: { mana: 3, attack: 160, special: "暴击" }, craftable: true },
  { id: "heaven_sword", name: "天堂之剑", category: "攻击", rarity: "epic", image: "images/heaven_sword.png", description: "造成100点伤害。暴击。", stats: { mana: 3, attack: 100, special: "暴击" }, craftable: true },
  { id: "hellfire", name: "地狱火", category: "攻击", rarity: "epic", image: "images/hellfire.png", description: "造成225点伤害，有几率击退。", stats: { mana: 3, attack: 225, special: "击退" }, craftable: true },
  { id: "no_future", name: "爆裂", category: "攻击", rarity: "epic", image: "images/no_future.png", description: "造成15点伤害。弹射并爆炸。", stats: { mana: 3, attack: 15, special: "弹射/爆炸" }, craftable: true },
  { id: "peachone", name: "白鸽", category: "攻击", rarity: "epic", image: "images/peachone.png", description: "造成100点伤害。每回合后轰炸敌人。", stats: { mana: 3, attack: 100, special: "每回合轰炸" }, craftable: false },
  { id: "phiera_der_tuphello", name: "图菲罗街市", category: "攻击", rarity: "epic", image: "images/phiera_der_tuphello.png", description: "造成70点伤害。", stats: { mana: 3, attack: 70 }, craftable: false },
  { id: "santa_water", name: "圣徒水", category: "攻击", rarity: "epic", image: "images/santa_water.png", description: "造成60点伤害。本回合后灼烧敌人。", stats: { mana: 3, attack: 60, special: "灼烧" }, craftable: false },
  { id: "shadow_pinion", name: "暗影螺钉", category: "攻击", rarity: "epic", image: "images/shadow_pinion.png", description: "造成90点伤害。连击。", stats: { mana: 3, attack: 90, special: "连击" }, craftable: false },
  { id: "soul_eater", name: "噬魂纹章", category: "攻击", rarity: "epic", image: "images/soul_eater.png", description: "对前排造成100点伤害。回复3点生命。缴械。", stats: { mana: 3, attack: 100, special: "回血/缴械" }, craftable: true },
  { id: "thousand_edge", name: "千刃", category: "攻击", rarity: "epic", image: "images/thousand_edge.png", description: "造成180点伤害。", stats: { mana: 3, attack: 180 }, craftable: true },

  // -- 4费 --
  { id: "ebony_wings", name: "黑翼", category: "攻击", rarity: "legendary", image: "images/ebony_wings.png", description: "造成140点伤害。每回合后轰炸敌人。", stats: { mana: 4, attack: 140, special: "每回合轰炸" }, craftable: false },
  { id: "la_borra", name: "圣徒精华", category: "攻击", rarity: "legendary", image: "images/la_borra.png", description: "造成150点伤害。每回合后灼烧敌人。", stats: { mana: 4, attack: 150, special: "每回合灼烧" }, craftable: true },
  { id: "phieraggi", name: "菲拉吉", category: "攻击", rarity: "legendary", image: "images/phieraggi.png", description: "造成350点伤害。", stats: { mana: 4, attack: 350 }, craftable: true },
  { id: "thunder_loop", name: "雷环", category: "攻击", rarity: "legendary", image: "images/thunder_loop.png", description: "造成150点伤害。回合结束时再次攻击。", stats: { mana: 4, attack: 150, special: "回合末再攻" }, craftable: true },

  // -- 5费 --
  { id: "mannajja", name: "黑乐谱", category: "攻击", rarity: "legendary", image: "images/mannajja.png", description: "对多个敌人造成79点伤害。原始法力。", stats: { mana: 5, attack: 79, special: "多目标/原始法力" }, craftable: true },
  { id: "pentagram", name: "五芒星", category: "攻击", rarity: "legendary", image: "images/pentagram.png", description: "抹除8行。倒计时。", stats: { mana: 5, attack: 999, special: "抹除8行" }, craftable: false },
  { id: "vandalier", name: "摧锋", category: "攻击", rarity: "legendary", image: "images/vandalier.png", description: "造成500点伤害，有几率击退。大鸟。", stats: { mana: 5, attack: 500, special: "击退/大鸟" }, craftable: true },

  // -- Wild --
  { id: "bracelet", name: "魔环", category: "攻击", rarity: "legendary", image: "images/bracelet.png", description: "造成100点伤害。", stats: { mana: "W", attack: 100, special: "Wild" }, craftable: false },

  // ═══════════════════════════════════════
  // 特殊类卡牌（Wild费用，10张）
  // ═══════════════════════════════════════
  { id: "big_coin_bag", name: "大钱袋", category: "特殊", image: "images/big_coin_bag.png", description: "获得25枚金币。消耗。", stats: { mana: "W", special: "金币+25/消耗" }, craftable: false },
  { id: "clover_petal", name: "四叶花瓣", category: "特殊", image: "images/clover_petal.png", description: "增加5%幸运。抽1张牌。消耗。", stats: { mana: "W", special: "幸运+5%/抽牌/消耗" }, craftable: false },
  { id: "coin_purse", name: "钱袋", category: "特殊", image: "images/coin_purse.png", description: "获得10枚金币。抽1张牌。消耗。", stats: { mana: "W", special: "金币+10/抽牌/消耗" }, craftable: false },
  { id: "little_clover", name: "小四叶草", category: "特殊", image: "images/little_clover.png", description: "增加10%幸运。消耗。", stats: { mana: "W", special: "幸运+10%/消耗" }, craftable: false },
  { id: "little_heart", name: "小爱心", category: "特殊", image: "images/little_heart.png", description: "回复1点生命。消耗。", stats: { mana: "W", special: "回血1/消耗" }, craftable: false },
  { id: "orologion", name: "时钟", category: "特殊", image: "images/orologion.png", description: "对前排施加1层冻结。消耗。", stats: { mana: "W", special: "冻结/消耗" }, craftable: false },
  { id: "raw_mana", name: "原始法力", category: "特殊", image: "images/raw_mana.png", description: "增加3点法力。消耗。临时。", stats: { mana: "W", special: "法力+3/消耗/临时" }, craftable: false },
  { id: "rich_coin_bag", name: "富豪钱袋", category: "特殊", image: "images/rich_coin_bag.png", description: "获得大量金币。消耗。", stats: { mana: "W", special: "金币++/消耗" }, craftable: false },
  { id: "rosary", name: "念珠", category: "特殊", image: "images/rosary.png", description: "消灭1行。消耗。", stats: { mana: "W", special: "灭行/消耗" }, craftable: false },
  { id: "vacuum", name: "吸尘器", category: "特殊", image: "images/vacuum.png", description: "抽1张牌。消耗。", stats: { mana: "W", special: "抽牌/消耗" }, craftable: false },

  // ═══════════════════════════════════════
  // 角色类卡牌（23张）
  // ═══════════════════════════════════════
  // -- 0费 --
  { id: "antonio", name: "安东尼奥", category: "角色", image: "images/antonio.png", description: "增加3点护甲。爬行者。", stats: { mana: 0, special: "护甲+3/爬行者" }, craftable: false },
  { id: "arca", name: "阿卡", category: "角色", image: "images/arca.png", description: "增加3点法力。爬行者。", stats: { mana: 0, special: "法力+3/爬行者" }, craftable: false },
  { id: "cavallo", name: "熊", category: "角色", image: "images/cavallo.png", description: "额外发射2个投射物。（2回合）爬行者。", stats: { mana: 0, special: "投射物+2/爬行者" }, craftable: false },
  { id: "christine", name: "克莉丝汀", category: "角色", image: "images/christine.png", description: "手中牌法力消耗-1。（9回合）爬行者。", stats: { mana: 0, special: "费用-1/爬行者" }, craftable: false },
  { id: "clerici", name: "克莱里奇", category: "角色", image: "images/clerici.png", description: "回复3点生命。爬行者。", stats: { mana: 0, special: "回血3/爬行者" }, craftable: false },
  { id: "imelda", name: "伊梅尔达", category: "角色", image: "images/imelda.png", description: "获得18点经验。爬行者。", stats: { mana: 0, special: "经验+18/爬行者" }, craftable: false },
  { id: "missingn0", name: "MissingN0", category: "角色", image: "images/missingn0.png", description: "增加4点护甲。爬行者。", stats: { mana: 0, special: "护甲+4/爬行者" }, craftable: false },
  { id: "mortaccio", name: "死东西", category: "角色", image: "images/mortaccio.png", description: "额外发射2个投射物。爬行者。", stats: { mana: 0, special: "投射物+2/爬行者" }, craftable: false },
  { id: "porta", name: "珀塔", category: "角色", image: "images/porta.png", description: "投射物命中次数+50%。（11回合）爬行者。", stats: { mana: 0, special: "命中+50%/爬行者" }, craftable: false },
  { id: "krochi", name: "柯洛奇", category: "角色", image: "images/krochi.png", description: "获得10%复活。爬行者。", stats: { mana: 0, special: "复活+10%/爬行者" }, craftable: false },
  { id: "lama", name: "拉玛", category: "角色", image: "images/lama.png", description: "伤害+50%。爬行者。", stats: { mana: 0, special: "伤害+50%/爬行者" }, craftable: false },
  { id: "pugnala", name: "普格纳拉", category: "角色", image: "images/pugnala.png", description: "伤害+20%。爬行者。", stats: { mana: 0, special: "伤害+20%/爬行者" }, craftable: false },
  // -- 1费 --
  { id: "concetta", name: "康雀妲", category: "角色", image: "images/concetta.png", description: "攻击造成10%溅射伤害。爬行者。", stats: { mana: 1, special: "溅射10%/爬行者" }, craftable: false },
  { id: "dommario", name: "多马利奥", category: "角色", image: "images/dommario.png", description: "爬行者触发更多能力后才离开。爬行者。", stats: { mana: 1, special: "持续+2/爬行者" }, craftable: false },
  { id: "gallo", name: "加洛", category: "角色", image: "images/gallo.png", description: "金币获取+25%。爬行者。", stats: { mana: 1, special: "金币+25%/爬行者" }, craftable: false },
  { id: "gennaro", name: "雅那略", category: "角色", image: "images/gennaro.png", description: "额外发射2个投射物。爬行者。", stats: { mana: 1, special: "投射物+2/爬行者" }, craftable: false },
  { id: "giovanna", name: "乔万娜", category: "角色", image: "images/giovanna.png", description: "增加20%幸运。爬行者。", stats: { mana: 1, special: "幸运+20%/爬行者" }, craftable: false },
  { id: "pasqualina", name: "帕斯姱丽娜", category: "角色", image: "images/pasqualina.png", description: "攻击造成10%溅射伤害。爬行者。", stats: { mana: 1, special: "溅射10%/爬行者" }, craftable: false },
  { id: "poe", name: "波", category: "角色", image: "images/poe.png", description: "攻击造成20%溅射伤害。爬行者。", stats: { mana: 1, special: "溅射20%/爬行者" }, craftable: false },
  { id: "poppea", name: "波佩阿", category: "角色", image: "images/poppea.png", description: "手牌上限+1。爬行者。", stats: { mana: 1, special: "手牌+1/爬行者" }, craftable: false },
  { id: "osole", name: "小太阳", category: "角色", image: "images/osole.png", description: "额外发射3个投射物。爬行者。", stats: { mana: 1, special: "投射物+3/爬行者" }, craftable: false },
  { id: "ramba", name: "兰巴", category: "角色", image: "images/ramba.png", description: "额外发射3个投射物。爬行者。", stats: { mana: 1, special: "投射物+3/爬行者" }, craftable: false },
  // -- 未使用 --
  { id: "divano", name: "迪瓦诺", category: "角色", image: "images/divano.png", description: "未使用角色。", stats: { mana: 0, special: "未使用" }, craftable: false },

  // ═══════════════════════════════════════
  // 临时类卡牌（7张）
  // ═══════════════════════════════════════
  { id: "angelo_spietato", name: "安杰洛·斯皮塔托", category: "临时", rarity: "legendary", image: "images/angelo_spietato.png", description: "回复3点生命。切割。消耗。临时。保留。", stats: { mana: 5, special: "回血/切割/临时/保留" }, craftable: false },
  { id: "confuse", name: "混乱", category: "临时", rarity: "common", image: "images/confuse.png", description: "法力消耗随机化。临时。", stats: { mana: 0, special: "法力随机/临时" }, craftable: false },
  { id: "cursed_lancet", name: "诅咒柳叶刀", category: "临时", rarity: "common", image: "images/cursed_lancet.png", description: "冻结下一张抽到的牌并增加其法力消耗。临时。", stats: { mana: 0, special: "冻结/加费/临时" }, craftable: false },
  { id: "junk", name: "废品", category: "临时", rarity: "common", image: "images/junk.png", description: "使用后销毁。抽1张牌。临时。", stats: { mana: 1, special: "抽牌/临时" }, craftable: false },
  { id: "mana_bomb", name: "法力炸弹", category: "临时", rarity: "legendary", image: "images/mana_bomb.png", description: "受到0点伤害。对前排造成0点伤害。法力炸弹。", stats: { mana: 5, special: "法力炸弹" }, craftable: false },
  { id: "muddle", name: "混乱", category: "临时", rarity: "common", image: "images/muddle.png", description: "爬行者触发类型随机化。临时。", stats: { mana: 0, special: "触发随机/临时" }, craftable: false },
  { id: "shatter", name: "粉碎", category: "临时", rarity: "common", image: "images/shatter.png", description: "临时卡牌。", stats: { mana: 0, special: "临时" }, craftable: false },

  // ═══════════════════════════════════════
  // 防御类卡牌（8张）
  // ═══════════════════════════════════════
  { id: "armor", name: "防御", category: "防御", rarity: "common", image: "images/armor.png", description: "增加2点护甲。", stats: { mana: 0, special: "护甲+2" }, craftable: false },
  { id: "clock_lancet", name: "时钟柳叶刀", category: "防御", rarity: "epic", image: "images/clock_lancet.png", description: "施加1层冻结。", stats: { mana: 3, special: "冻结" }, craftable: false },
  { id: "golden_armor", name: "黄金防御", category: "防御", rarity: "common", image: "images/golden_armor.png", description: "增加4点护甲。", stats: { mana: 1, special: "护甲+4" }, craftable: false },
  { id: "heros_armor", name: "英雄防御", category: "防御", rarity: "epic", image: "images/heros_armor.png", description: "增加8点护甲。", stats: { mana: 3, special: "护甲+8" }, craftable: false },
  { id: "parm_aegis", name: "帕尔姆神盾", category: "防御", rarity: "legendary", image: "images/parm_aegis.png", description: "增加1点护甲。", stats: { mana: "W", special: "护甲+1/Wild" }, craftable: false },
  { id: "pummadora", name: "愈伤番柿", category: "防御", rarity: "rare", image: "images/pummadora.png", description: "恢复：战斗后回复4点生命。", stats: { mana: 2, special: "战斗后回血4" }, craftable: false },
  { id: "pummarola", name: "愈伤番茄", category: "防御", rarity: "common", image: "images/pummarola.png", description: "恢复：战斗后回复2点生命。", stats: { mana: 1, special: "战斗后回血2" }, craftable: false },
  { id: "rainbow_armor", name: "彩虹防御", category: "防御", rarity: "rare", image: "images/rainbow_armor.png", description: "增加6点护甲。", stats: { mana: 2, special: "护甲+6" }, craftable: false },

  // ═══════════════════════════════════════
  // 属性增益类卡牌（19张）
  // ═══════════════════════════════════════
  { id: "attractorb", name: "念力法球", category: "属性", rarity: "common", image: "images/attractorb.png", description: "抽1张牌。", stats: { mana: 1, special: "抽牌" }, craftable: false },
  { id: "bracer", name: "护腕", category: "属性", rarity: "common", image: "images/bracer.png", description: "手牌上限+1。", stats: { mana: 0, special: "手牌+1" }, craftable: false },
  { id: "candelabrador", name: "烛台", category: "属性", rarity: "rare", image: "images/candelabrador.png", description: "攻击造成15%溅射伤害。", stats: { mana: 2, special: "溅射15%" }, craftable: false },
  { id: "candella", name: "双烛", category: "属性", rarity: "common", image: "images/candella.png", description: "攻击造成10%溅射伤害。", stats: { mana: 1, special: "溅射10%" }, craftable: false },
  { id: "candle", name: "蜡烛", category: "属性", rarity: "common", image: "images/candle.png", description: "攻击造成5%溅射伤害。", stats: { mana: 0, special: "溅射5%" }, craftable: false },
  { id: "clover", name: "四叶草", category: "属性", rarity: "rare", image: "images/clover.png", description: "增加10%幸运。", stats: { mana: 2, special: "幸运+10%" }, craftable: false },
  { id: "crown", name: "王冠", category: "属性", rarity: "common", image: "images/crown.png", description: "获得15%经验增长。消耗。", stats: { mana: 1, special: "经验+15%/消耗" }, craftable: false },
  { id: "crystal_crown", name: "水晶王冠", category: "属性", rarity: "rare", image: "images/crystal_crown.png", description: "获得20%经验增长。消耗。", stats: { mana: 2, special: "经验+20%/消耗" }, craftable: false },
  { id: "du_duplicator", name: "叕鸾宝镯", category: "属性", rarity: "rare", image: "images/du_duplicator.png", description: "额外发射2个投射物。", stats: { mana: 2, special: "投射物+2" }, craftable: false },
  { id: "duplicator", name: "双鸾宝镯", category: "属性", rarity: "common", image: "images/duplicator.png", description: "额外发射1个投射物。", stats: { mana: 1, special: "投射物+1" }, craftable: false },
  { id: "forever_heart", name: "永恒之心", category: "属性", rarity: "rare", image: "images/forever_heart.png", description: "获得1点最大生命。", stats: { mana: 2, special: "最大生命+1" }, craftable: false },
  { id: "friendship_amulet", name: "友谊护符", category: "属性", rarity: "legendary", image: "images/friendship_amulet.png", description: "增加连击。", stats: { mana: "W", special: "连击/Wild" }, craftable: false },
  { id: "hollow_heart", name: "空虚之心", category: "属性", rarity: "common", image: "images/hollow_heart.png", description: "获得3点最大生命。消耗。", stats: { mana: 1, special: "最大生命+3/消耗" }, craftable: false },
  { id: "skull_o_maniac", name: "疯狂骷髅", category: "属性", rarity: "common", image: "images/skull_o_maniac.png", description: "敌人强度+10%，获得额外经验。", stats: { mana: 0, special: "敌人+10%/额外经验" }, craftable: false },
  { id: "spellbinder", name: "咒缚盒", category: "属性", rarity: "common", image: "images/spellbinder.png", description: "爬行者触发更多能力后才离开。", stats: { mana: 0, special: "持续+2" }, craftable: false },
  { id: "spinach", name: "菠菜", category: "属性", rarity: "common", image: "images/spinach.png", description: "伤害+10%。", stats: { mana: 1, special: "伤害+10%" }, craftable: false },
  { id: "sprig_o_spinach", name: "老菠菜茎", category: "属性", rarity: "rare", image: "images/sprig_o_spinach.png", description: "伤害+20%。", stats: { mana: 2, special: "伤害+20%" }, craftable: false },
  { id: "stone_mask", name: "石面具", category: "属性", rarity: "common", image: "images/stone_mask.png", description: "金币获取+10%。消耗。", stats: { mana: 1, special: "金币+10%/消耗" }, craftable: false },
  { id: "tirajisu", name: "提拉吉苏", category: "属性", rarity: "rare", image: "images/tirajisu.png", description: "复活概率+10%。消耗。", stats: { mana: 2, special: "复活+10%/消耗" }, craftable: false },

  // ═══════════════════════════════════════
  // 法力类卡牌（6张）
  // ═══════════════════════════════════════
  { id: "empty_tome", name: "空白之书", category: "法力", rarity: "common", image: "images/empty_tome.png", description: "增加1点法力。", stats: { mana: 0, special: "法力+1" }, craftable: false },
  { id: "light_tome", name: "轻薄之书", category: "法力", rarity: "common", image: "images/light_tome.png", description: "增加2点法力。", stats: { mana: 1, special: "法力+2" }, craftable: false },
  { id: "weighty_tome", name: "厚重之书", category: "法力", rarity: "rare", image: "images/weighty_tome.png", description: "增加3点法力。", stats: { mana: 2, special: "法力+3" }, craftable: false },
  { id: "ancient_tome", name: "古老之书", category: "法力", rarity: "epic", image: "images/ancient_tome.png", description: "增加4点法力。", stats: { mana: 3, special: "法力+4" }, craftable: false },
  { id: "song_of_mana", name: "魔力歌谣", category: "法力", rarity: "legendary", image: "images/song_of_mana.png", description: "对多个敌人造成10点伤害。原始法力。法力增幅。", stats: { mana: 4, attack: 10, special: "多目标/原始法力/法力增幅" }, craftable: false },
  { id: "wings", name: "翅膀", category: "法力", rarity: "legendary", image: "images/wings.png", description: "下一张牌的法力消耗-1。", stats: { mana: "W", special: "法力消耗-1/Wild" }, craftable: false }
];


// ═══════════════════════════════════════
// 合成配方数据（17项）
// 数据来源：https://vampire.survivors.wiki/w/Crawlers:Evolution
// ═══════════════════════════════════════
const RECIPES = [
  { result: "bloody_tear", materials: ["whip", "hollow_heart"], count: { whip: 1, hollow_heart: 1 }, alternatives: { hollow_heart: ["forever_heart"] }, note: "进化：神鞭 + 空虚之心" },
  { result: "thousand_edge", materials: ["knife", "bracer"], count: { knife: 1, bracer: 1 }, note: "进化：飞刀 + 护腕" },
  { result: "holy_wand", materials: ["magic_wand", "empty_tome"], count: { magic_wand: 1, empty_tome: 1 }, alternatives: { empty_tome: ["light_tome", "weighty_tome", "ancient_tome"] }, note: "进化：强能魔杖 + 空白之书" },
  { result: "unholy_vespers", materials: ["king_bible", "spellbinder"], count: { king_bible: 1, spellbinder: 1 }, note: "进化：国王圣经 + 咒缚盒" },
  { result: "hellfire", materials: ["fire_wand", "spinach"], count: { fire_wand: 1, spinach: 1 }, alternatives: { spinach: ["sprig_o_spinach"] }, note: "进化：火焰魔杖 + 菠菜" },
  { result: "soul_eater", materials: ["garlic", "pummarola"], count: { garlic: 1, pummarola: 1 }, alternatives: { pummarola: ["pummadora"] }, note: "进化：大蒜 + 愈伤番茄" },
  { result: "death_spiral", materials: ["axe", "candelabrador"], count: { axe: 1, candelabrador: 1 }, alternatives: { candelabrador: ["candle", "candella"] }, note: "进化：斧头 + 烛台" },
  { result: "heaven_sword", materials: ["cross", "clover"], count: { cross: 1, clover: 1 }, note: "进化：十字飞镖 + 四叶草" },
  { result: "thunder_loop", materials: ["lightning_ring", "duplicator"], count: { lightning_ring: 1, duplicator: 1 }, alternatives: { duplicator: ["du_duplicator"] }, note: "进化：闪电戒指 + 双鸾宝镯" },
  { result: "no_future", materials: ["runetracer", "armor"], count: { runetracer: 1, armor: 1 }, alternatives: { armor: ["golden_armor", "rainbow_armor", "heros_armor"] }, note: "进化：痕印石 + 防御" },
  { result: "la_borra", materials: ["santa_water", "attractorb"], count: { santa_water: 1, attractorb: 1 }, note: "进化：圣徒水 + 念力法球" },
  { result: "vicious_hunger", materials: ["gatti_amari", "stone_mask"], count: { gatti_amari: 1, stone_mask: 1 }, note: "进化：彪悍猫 + 石面具" },
  { result: "mannajja", materials: ["song_of_mana", "skull_o_maniac"], count: { song_of_mana: 1, skull_o_maniac: 1 }, note: "进化：魔力歌谣 + 疯狂骷髅" },
  { result: "valkyrie_turner", materials: ["shadow_pinion", "wings"], count: { shadow_pinion: 1, wings: 1 }, note: "进化：暗影螺钉 + 翅膀" },
  { result: "gorgeous_moon", materials: ["pentagram", "crown"], count: { pentagram: 1, crown: 1 }, alternatives: { crown: ["crystal_crown"] }, note: "进化：五芒星 + 王冠" },
  { result: "phieraggi", materials: ["eight_the_sparrow", "phiera_der_tuphello", "tirajisu"], count: { eight_the_sparrow: 1, phiera_der_tuphello: 1, tirajisu: 1 }, note: "合一：麻雀小八 + 图菲罗街市 + 提拉吉苏" },
  { result: "vandalier", materials: ["peachone", "ebony_wings"], count: { peachone: 1, ebony_wings: 1 }, note: "合一：白鸽 + 黑翼" }
];


const PINYIN_MAP = {
  bone: "gt", knife: "fd", magic_wand: "qnmz", whip: "sb",
  cherry_bomb: "ytzb", fire_wand: "hymz", garlic: "ds", gatti_amari: "bhm",
  gorgeous_moon: "hywz", king_bible: "gjsj", runetracer: "hys",
  axe: "ft", bloody_tear: "xbc", carrello: "tc", celestial_dusting: "yhtl",
  cross: "szfb", eight_the_sparrow: "mqxb", holy_wand: "smmz",
  lightning_ring: "sdjz", unholy_vespers: "dsds", valkyrie_turner: "wejlp",
  vicious_hunger: "temy",
  death_spiral: "swxf", heaven_sword: "ttzj", hellfire: "dyh",
  no_future: "bl", peachone: "bg", phiera_der_tuphello: "tfljs",
  santa_water: "sts", shadow_pinion: "aylx", soul_eater: "shwz",
  thousand_edge: "qr",
  ebony_wings: "hy", la_borra: "stjy", phieraggi: "flj", thunder_loop: "lh",
  mannajja: "hlp", pentagram: "wmx", vandalier: "cf",
  bracelet: "mh",
  big_coin_bag: "dqd", clover_petal: "syhp", coin_purse: "qd",
  little_clover: "xsyc", little_heart: "xax", orologion: "sz",
  raw_mana: "ysfl", rich_coin_bag: "fhqd", rosary: "nz", vacuum: "xcq",
  antonio: "adn", arca: "ak", cavallo: "x", christine: "klst",
  clerici: "klq", imelda: "ymrd", missingn0: "MN", mortaccio: "sdx",
  porta: "pt", krochi: "klq", lama: "lm", pugnala: "pgnl",
  concetta: "kqd", dommario: "dmlo", gallo: "jl", gennaro: "gnr",
  giovanna: "qwn", pasqualina: "pskln", poe: "b", poppea: "bpa",
  osole: "xty", ramba: "lb", divano: "dwn",
  angelo_spietato: "ajl·sptt", confuse: "hl", cursed_lancet: "zwyld",
  junk: "fp", mana_bomb: "flzd", muddle: "hl", shatter: "fs",
  armor: "fy", clock_lancet: "zbyld", golden_armor: "hjfy",
  heros_armor: "yxfy", parm_aegis: "pmsd", pummadora: "ysfq",
  pummarola: "ysfq", rainbow_armor: "chfy",
  attractorb: "nlfq", bracer: "hw", candelabrador: "zt",
  candella: "sz", candle: "lz", clover: "syc", crown: "wg",
  crystal_crown: "sjwg", du_duplicator: "zlzbz", duplicator: "slzbz",
  forever_heart: "yhzx", friendship_amulet: "yyhf", hollow_heart: "kxzx",
  skull_o_maniac: "fkg", spellbinder: "zrh", spinach: "bc",
  sprig_o_spinach: "lbcz", stone_mask: "smm", tirajisu: "tljs",
  empty_tome: "kbzs", light_tome: "qbzs", weighty_tome: "hzbs",
  ancient_tome: "glzs", song_of_mana: "mlgy", wings: "cb"
};


// ═══════════════════════════════════════
// 卡牌详细描述（攻击类，来源wiki）
// 使用 <ref id="card_id">名称</ref> 标记可点击卡牌引用
// 使用 <b>数字</b> 标记重要数值
// 使用 <em>机制</em> 标记特殊机制
// ═══════════════════════════════════════
const CARD_DETAILS = {
  axe: '<p>初始拥有<b>1</b>个宝石槽，默认解锁。出现在升级奖励中的最低等级为<b>11</b>。</p><p>可进化为<ref id="death_spiral">死亡旋风</ref>，需要<ref id="candle">蜡烛</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>3</b>，每发弹射物对最多两个敌人造成<b>15</b>点基础伤害。按从右到左的顺序攻击前排敌人，每发弹射物命中一个敌人<em>及其右侧的敌人</em>（最右侧的敌人会绕到最左侧）。下一颗弹射物不会重复命中上一颗已命中的敌人。若仅剩单个敌人，每发弹射物只命中一次。当一行中最左侧敌人已被命中后，多余的弹射物从该行右侧重新开始；只有当一行敌人全部消灭后才会攻击下一行。</p>',
  bloody_tear: '<p>通过进化<ref id="whip">神鞭</ref>解锁。由<ref id="whip">神鞭</ref>进化而来，需要<ref id="hollow_heart">空虚之心</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>10</b>，每发弹射物对所有前方没有其他敌人挡住的敌人造成<b>4</b>点基础伤害。每次伤害实例（而非每发弹射物）有几率<em>暴击</em>，造成<b>2倍</b>伤害（例如无其他加成时从4变为8）。只要打出时存在至少一次暴击，就回复<b>3</b>点生命值，回复量不随暴击次数增加。</p>',
  bone: '<p>出现在升级奖励中的最低等级为<b>1</b>。</p>',
  bracelet: '<p>出现在升级奖励中的最低等级为<b>30</b>。</p>',
  carrello: '<p>出现在升级奖励中的最低等级为<b>11</b>。</p>',
  celestial_dusting: '<p>出现在升级奖励中的最低等级为<b>11</b>。</p>',
  cherry_bomb: '<p>出现在升级奖励中的最低等级为<b>1</b>。</p>',
  cross: '<p>出现在升级奖励中的最低等级为<b>11</b>。</p><p>可进化为<ref id="heaven_sword">天堂之剑</ref>，需要<ref id="clover">四叶草</ref>组卡牌和进化宝石。</p>',
  death_spiral: '<p>由<ref id="axe">斧头</ref>进化而来，需要<ref id="candle">蜡烛</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>16</b>，每发弹射物对前排每个敌人造成<b>10</b>点基础伤害。不会攻击非前排的敌人，即使前方没有其他敌人挡着。每次伤害实例有几率<em>暴击</em>，造成<b>2倍</b>伤害（例如无其他加成时从10变为20）。</p>',
  ebony_wings: '<p>出现在升级奖励中的最低等级为<b>30</b>。</p><p>可进化为<ref id="vandalier">摧锋</ref>，需要<ref id="peachone">白鸽</ref>和进化宝石。</p>',
  eight_the_sparrow: '<p>出现在升级奖励中的最低等级为<b>11</b>。</p><p>可进化为<ref id="phieraggi">菲拉吉</ref>，需要<ref id="phiera_der_tuphello">图菲罗街市</ref>加上<ref id="tirajisu">提拉吉苏</ref>组卡牌和进化宝石。</p>',
  fire_wand: '<p>初始拥有<b>1</b>个宝石槽。出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="hellfire">地狱火</ref>，需要<ref id="spinach">菠菜</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>3</b>，每发弹射物造成<b>15</b>点基础伤害。<em>随机攻击前方无敌人的敌人。</em></p>',
  garlic: '<p>初始拥有<b>1</b>个宝石槽。出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="soul_eater">噬魂纹章</ref>，需要<ref id="pummarola">愈伤番茄</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>1</b>，对前排每个敌人造成<b>10</b>点基础伤害。不会攻击非前排的敌人，即使前方没有其他敌人挡着。<em>不享受任何发射数量加成。</em></p>',
  gatti_amari: '<p>出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="vicious_hunger">饕恶魔眼</ref>，需要<ref id="stone_mask">石面具</ref>组卡牌和进化宝石。</p><h4>特殊机制</h4><p><em>混战</em>：两只猫相撞时可能开始打架。</p>',
  gorgeous_moon: '<p>由<ref id="pentagram">五芒星</ref>进化而来，需要<ref id="crown">王冠</ref>组卡牌和进化宝石。</p><h4>特殊机制</h4><p><em>抹除</em>：消灭敌人并获得额外经验。</p><p><em>月升</em>：华月纹章变强但法力消耗增加（累计消耗<b>5</b>点法力后重置为<b>1</b>）。</p>',
  heaven_sword: '<p>由<ref id="cross">十字飞镖</ref>进化而来，需要<ref id="clover">四叶草</ref>组卡牌和进化宝石。</p><h4>特殊机制</h4><p><em>暴击</em>：有几率造成倍率伤害。</p>',
  hellfire: '<p>由<ref id="fire_wand">火焰魔杖</ref>进化而来，需要<ref id="spinach">菠菜</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>15</b>，每发弹射物造成<b>15</b>点基础伤害。<em>随机攻击前方无敌人的敌人。</em></p>',
  holy_wand: '<p>由<ref id="magic_wand">强能魔杖</ref>进化而来，需要<ref id="empty_tome">空白之书</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>10</b>，每发弹射物造成<b>15</b>点基础伤害。按从右到左顺序攻击，<em>优先攻击即将行动的敌人</em>。当一行中最左侧敌人已被命中后，多余的弹射物从该行右侧重新开始；只有当一行敌人全部消灭后才会攻击下一行。</p>',
  king_bible: '<p>初始拥有<b>1</b>个宝石槽。出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="unholy_vespers">渎神祷书</ref>，需要<ref id="spellbinder">咒缚盒</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>5</b>，每发弹射物造成<b>8</b>点基础伤害。按从左到右顺序攻击前排敌人。当一行中最右侧敌人已被命中后，多余的弹射物从该行左侧重新开始。不会攻击非前排的敌人，即使前方没有其他敌人挡着。</p>',
  knife: '<p>初始拥有<b>1</b>个宝石槽。出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="thousand_edge">千刃</ref>，需要<ref id="bracer">护腕</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>5</b>，每发弹射物造成<b>8</b>点基础伤害。按从右到左顺序攻击，从最前排开始。当一行中最左侧敌人已被命中后，多余的弹射物从该行右侧重新开始；只有当一行敌人全部消灭后才会攻击下一行。</p>',
  la_borra: '<p>由<ref id="santa_water">圣徒水</ref>进化而来，需要<ref id="attractorb">念力法球</ref>组卡牌和进化宝石。</p>',
  lightning_ring: '<p>出现在升级奖励中的最低等级为<b>11</b>。</p><p>可进化为<ref id="thunder_loop">雷环</ref>，需要<ref id="duplicator">双鸾宝镯</ref>组卡牌和进化宝石。</p>',
  magic_wand: '<p>存在于伊梅尔达的初始牌组中。初始拥有<b>1</b>个宝石槽，默认解锁。出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="holy_wand">神授魔杖</ref>，需要<ref id="empty_tome">空白之书</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>1</b>，造成<b>30</b>点基础伤害。按从右到左顺序攻击，<em>优先攻击即将行动的敌人</em>。当一行中最左侧敌人已被命中后，多余的弹射物从该行右侧重新开始；只有当一行敌人全部消灭后才会攻击下一行。</p>',
  mannajja: '<p>由<ref id="song_of_mana">魔力歌谣</ref>进化而来，需要<ref id="skull_o_maniac">疯狂骷髅</ref>组卡牌和进化宝石。</p><h4>特殊机制</h4><p><em>原始法力</em>：有几率将<b>2</b>张法力牌加入手牌。</p>',
  no_future: '<p>由<ref id="runetracer">痕印石</ref>进化而来，需要<ref id="armor">防御</ref>组卡牌和进化宝石。</p>',
  peachone: '<p>出现在升级奖励中的最低等级为<b>20</b>。</p><p>可进化为<ref id="vandalier">摧锋</ref>，需要<ref id="ebony_wings">黑翼</ref>和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>1</b>，每只鸽子（每发弹射物）造成<b>5</b>次独立伤害，每次<b>20</b>点基础伤害，再加上每多一只鸽子就多一次伤害实例。举例：加成发射数量为1时，2只鸽子各攻击<b>6</b>次；加成为2时，3只各攻击<b>7</b>次；加成为3时，4只各攻击<b>8</b>次。这意味着白鸽的伤害随发射数量呈<em>二次方增长</em>，是试玩版中攻击牌里成长性最强的。每次伤害实例按从右到左顺序攻击，从最前排开始；多余的实例从该行右侧重新开始，只有当一行敌人全部消灭后才会攻击下一行。</p>',
  pentagram: '<p>出现在升级奖励中的最低等级为<b>40</b>。</p><p>可进化为<ref id="gorgeous_moon">华月纹章</ref>，需要<ref id="crown">王冠</ref>组卡牌和进化宝石。</p>',
  phiera_der_tuphello: '<p>出现在升级奖励中的最低等级为<b>20</b>。</p><p>可进化为<ref id="phieraggi">菲拉吉</ref>，需要<ref id="eight_the_sparrow">麻雀小八</ref>加上<ref id="tirajisu">提拉吉苏</ref>组卡牌和进化宝石。</p>',
  phieraggi: '<p>由<ref id="eight_the_sparrow">麻雀小八</ref>和<ref id="phiera_der_tuphello">图菲罗街市</ref>进化而来，需要<ref id="tirajisu">提拉吉苏</ref>组卡牌和进化宝石。</p>',
  runetracer: '<p>初始拥有<b>1</b>个宝石槽。出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="no_future">爆裂</ref>，需要<ref id="armor">防御</ref>组卡牌和进化宝石。</p>',
  santa_water: '<p>初始拥有<b>1</b>个宝石槽。出现在升级奖励中的最低等级为<b>20</b>。</p><p>可进化为<ref id="la_borra">圣徒精华</ref>，需要<ref id="attractorb">念力法球</ref>组卡牌和进化宝石。</p>',
  shadow_pinion: '<p>出现在升级奖励中的最低等级为<b>20</b>。</p><p>可进化为<ref id="valkyrie_turner">瓦尔基里喷枪</ref>，需要<ref id="wings">翅膀</ref>组卡牌和进化宝石。</p>',
  soul_eater: '<p>由<ref id="garlic">大蒜</ref>进化而来，需要<ref id="pummarola">愈伤番茄</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>1</b>，对前排每个敌人造成<b>100</b>点基础伤害。不会攻击非前排的敌人，即使前方没有其他敌人挡着。<em>不享受任何发射数量加成。</em></p>',
  thousand_edge: '<p>由<ref id="knife">飞刀</ref>进化而来，需要<ref id="bracer">护腕</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>20</b>，每发弹射物造成<b>9</b>点基础伤害。按从右到左顺序攻击，从最前排开始。当一行中最左侧敌人已被命中后，多余的弹射物从该行右侧重新开始；只有当一行敌人全部消灭后才会攻击下一行。</p>',
  thunder_loop: '<p>由<ref id="lightning_ring">闪电戒指</ref>进化而来，需要<ref id="duplicator">双鸾宝镯</ref>组卡牌和进化宝石。</p>',
  unholy_vespers: '<p>由<ref id="king_bible">国王圣经</ref>进化而来，需要<ref id="spellbinder">咒缚盒</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>10</b>，每发弹射物造成<b>12</b>点基础伤害。按从左到右顺序攻击前排敌人。当一行中最右侧敌人已被命中后，多余的弹射物从该行左侧重新开始。不会攻击非前排的敌人，即使前方没有其他敌人挡着。</p>',
  valkyrie_turner: '<p>由<ref id="shadow_pinion">暗影螺钉</ref>进化而来，需要<ref id="wings">翅膀</ref>组卡牌和进化宝石。</p><h4>特殊机制</h4><p><em>瓦尔基里之炎</em>：使用后，每打出一张牌都会为该牌充能伤害。</p>',
  vandalier: '<p>由<ref id="peachone">白鸽</ref>和<ref id="ebony_wings">黑翼</ref>进化而来，需要进化宝石。</p><h4>特殊机制</h4><p><em>击退</em>：阻止敌人下回合攻击。</p><p><em>大鸟</em>：驱散所有活跃的鸟，造成更高伤害。</p>',
  vicious_hunger: '<p>由<ref id="gatti_amari">彪悍猫</ref>进化而来，需要<ref id="stone_mask">石面具</ref>组卡牌和进化宝石。</p>',
  whip: '<p>存在于安东尼奥的初始牌组中。初始拥有<b>1</b>个宝石槽，默认解锁。出现在升级奖励中的最低等级为<b>1</b>。</p><p>可进化为<ref id="bloody_tear">血笞</ref>，需要<ref id="hollow_heart">空虚之心</ref>组卡牌和进化宝石。</p><h4>攻击机制</h4><p>发射数量基础为<b>1</b>，对所有前方没有其他敌人挡住的敌人造成<b>8</b>点基础伤害。</p>',

  // ═══════════════════════════════════════
  // 防御类卡牌
  // ═══════════════════════════════════════
  armor: '<p>出现在升级奖励中的最低等级为<b>1</b>。</p><p>属于<ref id="armor">防御</ref>进化组的第一级。</p><h4>效果</h4><p>增加<b>2</b>点护甲。在售货机中献祭时，每回合额外增加<b>1</b>点护甲直到战斗结束。</p>',
  clock_lancet: '<p>出现在升级奖励中的最低等级为<b>20</b>，拥有<b>1</b>个宝石槽。通过找到并打出<ref id="orologion">时钟</ref>解锁。</p><h4>效果</h4><p>冻结<b>X</b>个敌人，数量随当前<em>连击数</em>缩放。与其他卡牌不同，目前<em>无法镶嵌万能宝石</em>。</p>',
  golden_armor: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过打出<b>10</b>张<ref id="armor">防御</ref>卡牌解锁。</p><p>属于<ref id="armor">防御</ref>进化组的第二级。</p><h4>效果</h4><p>增加<b>4</b>点护甲。在售货机中献祭时，每回合额外增加<b>2</b>点护甲直到战斗结束。</p>',
  heros_armor: '<p>出现在升级奖励中的最低等级为<b>20</b>，拥有<b>1</b>个宝石槽。</p><p>属于<ref id="armor">防御</ref>进化组的第四级。<em>已从游戏中移除</em>，尽管在正式版中更新了图标，但无法再从卡牌池中获取。</p><h4>效果</h4><p>增加<b>8</b>点护甲。</p>',
  parm_aegis: '<p>出现在升级奖励中的最低等级为<b>20</b>。通过达到<b>12</b>连击或更高解锁。</p><h4>效果</h4><p>增加<b>1</b>点护甲。在售货机中献祭时，每回合额外增加<b>1</b>点护甲直到战斗结束。</p>',
  pummadora: '<p>出现在升级奖励中的最低等级为<b>11</b>。通过打出<b>100</b>张<ref id="pummarola">愈伤番茄</ref>卡牌解锁。</p><p>属于<ref id="pummarola">愈伤番茄</ref>进化组的第二级。</p><h4>效果</h4><p><em>恢复</em>：战斗后回复<b>4</b>点生命值。</p>',
  pummarola: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过使用雅那略达到<b>10</b>级解锁。</p><p>属于<ref id="pummarola">愈伤番茄</ref>进化组的第一级。</p><h4>效果</h4><p><em>恢复</em>：战斗后回复<b>2</b>点生命值。</p>',
  rainbow_armor: '<p>出现在升级奖励中的最低等级为<b>11</b>。通过打出<b>100</b>张<ref id="armor">防御</ref>卡牌解锁。</p><p>属于<ref id="armor">防御</ref>进化组的第三级。</p><h4>效果</h4><p>增加<b>6</b>点护甲。在售货机中献祭时，每回合额外增加<b>3</b>点护甲直到战斗结束。</p>',

  // ═══════════════════════════════════════
  // 属性增益类卡牌
  // ═══════════════════════════════════════
  attractorb: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过找到并打出<b>1</b>张<ref id="vacuum">吸尘器</ref>解锁。</p><p>属于<ref id="attractorb">念力法球</ref>进化组。</p><h4>效果</h4><p>抽<b>1</b>张牌。</p>',
  bracer: '<p>出现在升级奖励中的最低等级为<b>11</b>，拥有<b>1</b>个宝石槽。通过打出<b>99</b>张<ref id="king_bible">国王圣经</ref>卡牌解锁。</p><p>属于<ref id="bracer">护腕</ref>进化组。</p><h4>效果</h4><p><em>手牌</em>：手牌上限增加<b>1</b>。</p>',
  candelabrador: '<p>出现在升级奖励中的最低等级为<b>11</b>。通过打出<b>3</b>张<ref id="santa_water">圣徒水</ref>卡牌解锁。</p><p>属于<ref id="candle">蜡烛</ref>进化组的第三级。可将<ref id="axe">斧头</ref>进化为<ref id="death_spiral">死亡旋风</ref>。在售货机中献祭时，永久增加<b>15%</b>攻击范围。</p><h4>效果</h4><p>攻击造成<b>15%</b>溅射伤害。</p>',
  candella: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过打出<b>40</b>张<ref id="candelabrador">烛台</ref>卡牌解锁。</p><p>属于<ref id="candle">蜡烛</ref>进化组的第二级。可将<ref id="axe">斧头</ref>进化为<ref id="death_spiral">死亡旋风</ref>。在售货机中献祭时，永久增加<b>10%</b>攻击范围。</p><h4>效果</h4><p><em>范围</em>：攻击造成<b>10%</b>溅射伤害。</p>',
  candle: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过打出<b>20</b>张<ref id="candelabrador">烛台</ref>卡牌解锁。</p><p>属于<ref id="candle">蜡烛</ref>进化组的第一级。可将<ref id="axe">斧头</ref>进化为<ref id="death_spiral">死亡旋风</ref>。</p><h4>效果</h4><p><em>范围</em>：攻击造成<b>5%</b>溅射伤害。</p>',
  clover: '<p>出现在升级奖励中的最低等级为<b>11</b>，拥有<b>1</b>个宝石槽。通过找到并打出<b>10</b>张<ref id="little_clover">小四叶草</ref>卡牌解锁。</p><p>属于<ref id="clover">四叶草</ref>进化组。可将<ref id="cross">十字飞镖</ref>进化为<ref id="heaven_sword">天堂之剑</ref>。</p><h4>效果</h4><p>增加<b>10%</b>幸运。</p>',
  crown: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过达到<b>15</b>级解锁。</p><p>属于<ref id="crown">王冠</ref>进化组的第一级。可将<ref id="pentagram">五芒星</ref>进化为<ref id="gorgeous_moon">华月纹章</ref>。</p><h4>效果</h4><p><em>成长</em>：获得<b>15%</b>经验增长。<em>销毁</em>。</p>',
  crystal_crown: '<p>出现在升级奖励中的最低等级为<b>11</b>，拥有<b>1</b>个宝石槽。通过打出<b>200</b>张<ref id="crown">王冠</ref>卡牌解锁。</p><p>属于<ref id="crown">王冠</ref>进化组的第二级。可将<ref id="pentagram">五芒星</ref>进化为<ref id="gorgeous_moon">华月纹章</ref>。</p><h4>效果</h4><p><em>成长</em>：获得<b>20%</b>经验增长。<em>销毁</em>。</p>',
  du_duplicator: '<p>出现在升级奖励中的最低等级为<b>11</b>，拥有<b>1</b>个宝石槽。通过打出<b>100</b>张<ref id="duplicator">双鸾宝镯</ref>卡牌解锁。</p><p>属于<ref id="duplicator">双鸾宝镯</ref>进化组的第二级。可将<ref id="lightning_ring">闪电戒指</ref>进化为<ref id="thunder_loop">雷环</ref>。</p><h4>效果</h4><p>额外发射<b>2</b>个投射物。</p>',
  duplicator: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过打出<b>25</b>张<ref id="magic_wand">强能魔杖</ref>卡牌解锁。</p><p>属于<ref id="duplicator">双鸾宝镯</ref>进化组的第一级。可将<ref id="lightning_ring">闪电戒指</ref>进化为<ref id="thunder_loop">雷环</ref>。</p><h4>效果</h4><p><em>数量</em>：额外发射<b>1</b>个投射物。</p>',
  forever_heart: '<p>出现在升级奖励中的最低等级为<b>11</b>，拥有<b>1</b>个宝石槽。通过打出<b>25</b>张<ref id="hollow_heart">空虚之心</ref>卡牌解锁。</p><p>属于<ref id="hollow_heart">空虚之心</ref>进化组的第二级。可将<ref id="whip">神鞭</ref>进化为<ref id="bloody_tear">血笞</ref>。</p><h4>效果</h4><p>获得<b>1</b>点最大生命值。</p>',
  friendship_amulet: '<p>出现在升级奖励中的最低等级为<b>20</b>。通过达到<b>7</b>连击或更高解锁。</p><h4>效果</h4><p>增加连击数。</p>',
  hollow_heart: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过达到<b>10</b>级解锁。</p><p>属于<ref id="hollow_heart">空虚之心</ref>进化组的第一级。可将<ref id="whip">神鞭</ref>进化为<ref id="bloody_tear">血笞</ref>。</p><h4>效果</h4><p>获得<b>3</b>点最大生命值。<em>销毁</em>。</p>',
  skull_o_maniac: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过使用拉玛达到<b>30</b>级解锁。</p><p>属于<ref id="skull_o_maniac">疯狂骷髅</ref>进化组。可将<ref id="song_of_mana">魔力歌谣</ref>进化为<ref id="mannajja">黑乐谱</ref>。</p><h4>效果</h4><p>敌人强度增加<b>10%</b>，获得额外经验。</p>',
  spellbinder: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过打出<b>10</b>张<ref id="runetracer">痕印石</ref>卡牌解锁。</p><p>属于<ref id="spellbinder">咒缚盒</ref>进化组。可将<ref id="king_bible">国王圣经</ref>进化为<ref id="unholy_vespers">渎神祷书</ref>。</p><h4>效果</h4><p><em>持续</em>：爬行者触发更多能力后才离开（+<b>2</b>次）。</p>',
  spinach: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过打出<b>30</b>张<ref id="spinach">菠菜</ref>卡牌解锁。</p><p>属于<ref id="spinach">菠菜</ref>进化组的第一级。可将<ref id="fire_wand">火焰魔杖</ref>进化为<ref id="hellfire">地狱火</ref>。力量达到<b>1000%</b>后无法再增加。</p><h4>效果</h4><p><em>力量</em>：伤害增加<b>10%</b>。</p>',
  sprig_o_spinach: '<p>出现在升级奖励中的最低等级为<b>11</b>，拥有<b>1</b>个宝石槽。通过打出<b>60</b>张<ref id="spinach">菠菜</ref>卡牌解锁。</p><p>属于<ref id="spinach">菠菜</ref>进化组的第二级。可将<ref id="fire_wand">火焰魔杖</ref>进化为<ref id="hellfire">地狱火</ref>。力量达到<b>1000%</b>后无法再增加。</p><h4>效果</h4><p>伤害增加<b>20%</b>。</p>',
  stone_mask: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过找到并打出一张<ref id="stone_mask">石面具</ref>卡牌解锁。</p><p>属于<ref id="stone_mask">石面具</ref>进化组。可将<ref id="gatti_amari">彪悍猫</ref>进化为<ref id="vicious_hunger">饕恶魔眼</ref>。贪欲达到<b>1000%</b>后无法再增加。</p><h4>效果</h4><p><em>贪欲</em>：金币获取增加<b>10%</b>。<em>销毁</em>。</p>',
  tirajisu: '<p>出现在升级奖励中的最低等级为<b>11</b>。通过使用柯洛奇达到<b>20</b>级解锁。</p><p>属于<ref id="tirajisu">提拉吉苏</ref>进化组。可将<ref id="eight_the_sparrow">麻雀小八</ref>和<ref id="phiera_der_tuphello">图菲罗街市</ref>进化为<ref id="phieraggi">菲拉吉</ref>。</p><h4>效果</h4><p><em>复活</em>：复活概率增加<b>10%</b>。<em>销毁</em>。</p>',

  // ═══════════════════════════════════════
  // 法力类卡牌
  // ═══════════════════════════════════════
  empty_tome: '<p>出现在升级奖励中的最低等级为<b>1</b>。通过收集<b>2</b>个法力球解锁。</p><p>属于<ref id="empty_tome">空白之书</ref>进化组的第一级。可将<ref id="magic_wand">强能魔杖</ref>进化为<ref id="holy_wand">神授魔杖</ref>。</p><h4>效果</h4><p>增加<b>1</b>点法力。</p>',
  light_tome: '<p>出现在升级奖励中的最低等级为<b>1</b>，拥有<b>1</b>个宝石槽。通过打出<b>30</b>张<ref id="empty_tome">空白之书</ref>卡牌解锁。</p><p>属于<ref id="empty_tome">空白之书</ref>进化组的第二级。可将<ref id="magic_wand">强能魔杖</ref>进化为<ref id="holy_wand">神授魔杖</ref>。</p><h4>效果</h4><p>增加<b>2</b>点法力。</p>',
  weighty_tome: '<p>出现在升级奖励中的最低等级为<b>11</b>，拥有<b>2</b>个宝石槽。通过打出<b>60</b>张<ref id="empty_tome">空白之书</ref>卡牌解锁。</p><p>属于<ref id="empty_tome">空白之书</ref>进化组的第三级。可将<ref id="magic_wand">强能魔杖</ref>进化为<ref id="holy_wand">神授魔杖</ref>。</p><h4>效果</h4><p>增加<b>3</b>点法力。</p>',
  ancient_tome: '<p>出现在升级奖励中的最低等级为<b>20</b>，拥有<b>3</b>个宝石槽。通过打出<b>300</b>张<ref id="empty_tome">空白之书</ref>卡牌解锁。</p><p>属于<ref id="empty_tome">空白之书</ref>进化组的第四级。可将<ref id="magic_wand">强能魔杖</ref>进化为<ref id="holy_wand">神授魔杖</ref>。</p><h4>效果</h4><p>增加<b>4</b>点法力。</p>',
  song_of_mana: '<p>出现在升级奖励中的最低等级为<b>30</b>，拥有<b>1</b>个宝石槽。通过使用波佩阿达到<b>30</b>级解锁。</p><p>可进化为<ref id="mannajja">黑乐谱</ref>，需要<ref id="skull_o_maniac">疯狂骷髅</ref>组卡牌和进化宝石。</p><h4>效果</h4><p>对多个敌人造成<b>10</b>点伤害。<em>原始法力</em>。<em>法力增幅</em>。</p>',
  wings: '<p>出现在升级奖励中的最低等级为<b>30</b>。通过达到<b>40</b>级解锁。</p><p>属于<ref id="wings">翅膀</ref>进化组。可将<ref id="shadow_pinion">暗影螺钉</ref>进化为<ref id="valkyrie_turner">瓦尔基里喷枪</ref>。</p><h4>效果</h4><p>下一张打出的卡牌法力消耗减少<b>1</b>。</p>',

  // ═══════════════════════════════════════
  // Wild卡牌（特殊类）
  // ═══════════════════════════════════════
  big_coin_bag: '<p>通过破坏光源或打出带有<em>金币卡牌</em>宝石的卡牌获得。</p><h4>效果</h4><p>获得<b>25</b>枚金币。<em>销毁</em>。</p>',
  clover_petal: '<p>通过打出<b>5</b>张<ref id="little_clover">小四叶草</ref>卡牌解锁。</p><h4>效果</h4><p>增加<b>5%</b>幸运。抽<b>1</b>张牌。<em>销毁</em>。</p>',
  coin_purse: '<p>通过打出<b>5</b>张<ref id="big_coin_bag">大钱袋</ref>卡牌解锁。</p><h4>效果</h4><p>获得<b>10</b>枚金币。抽<b>1</b>张牌。<em>销毁</em>。</p>',
  little_clover: '<p>默认解锁。</p><h4>效果</h4><p>增加<b>10%</b>幸运。<em>销毁</em>。</p>',
  little_heart: '<p>默认解锁。</p><h4>效果</h4><p>回复<b>1</b>点生命值。<em>销毁</em>。</p>',
  orologion: '<p>通过打出<b>30</b>张Wild卡牌解锁。</p><p>可解锁<ref id="clock_lancet">时钟柳叶刀</ref>。</p><h4>效果</h4><p>对前排施加<b>1</b>层冻结。<em>销毁</em>。</p>',
  raw_mana: '<p>默认解锁。</p><h4>效果</h4><p>增加<b>3</b>点法力。<em>销毁</em>。<em>临时</em>。</p>',
  rich_coin_bag: '<p>通过打出<b>30</b>张<ref id="big_coin_bag">大钱袋</ref>卡牌解锁。通过破坏光源获得。</p><h4>效果</h4><p>获得大量金币。<em>销毁</em>。</p>',
  rosary: '<p>通过打出<b>20</b>张Wild卡牌解锁。可解锁<ref id="cross">十字飞镖</ref>。</p><h4>效果</h4><p>消灭<b>1</b>行敌人。<em>销毁</em>。</p>',
  vacuum: '<p>通过破坏<b>30</b>个光源解锁。可解锁<ref id="attractorb">念力法球</ref>。</p><h4>效果</h4><p>抽<b>1</b>张牌。<em>销毁</em>。</p>',

  // ═══════════════════════════════════════
  // 临时类卡牌
  // ═══════════════════════════════════════
  angelo_spietato: '<p>费用<b>5</b>。</p><h4>效果</h4><p>回复<b>3</b>点生命值。<em>切割</em>。<em>销毁</em>。<em>临时</em>。<em>保留</em>。</p>',
  confuse: '<p>费用<b>0</b>。抽到时<em>自动打出</em>。</p><h4>效果</h4><p>所有卡牌的法力消耗随机化。<em>临时</em>。</p>',
  cursed_lancet: '<p>费用<b>0</b>。</p><h4>效果</h4><p>冻结下一张抽到的卡牌并增加其法力消耗。<em>临时</em>。</p>',
  junk: '<p>费用<b>1</b>。</p><h4>效果</h4><p>使用后销毁。抽<b>1</b>张牌。<em>临时</em>。</p>',
  mana_bomb: '<p>费用<b>5</b>。</p><h4>效果</h4><p>受到<b>0</b>点伤害。对前排造成<b>0</b>点伤害。<em>法力炸弹</em>。</p>',
  muddle: '<p>费用<b>0</b>。抽到时<em>自动打出</em>。</p><h4>效果</h4><p>爬行者触发类型随机化。<em>临时</em>。</p>',
  shatter: '<p>费用<b>0</b>。<em>临时</em>卡牌。</p>',

  // ═══════════════════════════════════════
  // 角色类卡牌
  // ═══════════════════════════════════════
  antonio: '<p>费用<b>0</b>。通过完成教程解锁。购买费用<b>0</b>金币。</p><h4>卡牌效果</h4><p>增加<b>3</b>点护甲。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出红色卡牌时，伤害增加<b>10%</b>。持续<b>5</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+10</b>。</p>',
  arca: '<p>费用<b>0</b>。通过打出<b>100</b>张<ref id="fire_wand">火焰魔杖</ref>卡牌解锁。购买费用<b>500</b>金币。</p><h4>卡牌效果</h4><p>增加<b>3</b>点法力。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出紫色卡牌时，增加<b>1</b>点法力。持续<b>5</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+5</b>，法力<b>+1</b>，力量<b>+30%</b>。</p>',
  cavallo: '<p>费用<b>0</b>。通过击败<b>250</b>个狮头解锁。购买费用<b>750</b>金币。</p><h4>卡牌效果</h4><p>额外发射<b>2</b>个投射物（<b>2</b>回合持续）。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出黄色卡牌时，增加<b>1</b>个发射数量。持续<b>2</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+20</b>，手牌<b>+1</b>，发射数量<b>+2</b>。</p>',
  christine: '<p>费用<b>0</b>。通过找到并打出<ref id="pentagram">五芒星</ref>解锁。</p><h4>卡牌效果</h4><p>手中所有卡牌法力消耗减少<b>1</b>（<b>9</b>回合持续）。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出紫色卡牌时，缴械<b>1</b>个敌人。持续<b>3</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+2</b>，幸运<b>+50%</b>，成长<b>+25%</b>，重掷<b>+3</b>，跳过<b>+3</b>。</p>',
  clerici: '<p>费用<b>0</b>。通过累计回复<b>1,000</b>点生命值解锁。</p><h4>卡牌效果</h4><p>回复<b>3</b>点生命值。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出蓝色卡牌时，战斗后回复<b>1</b>点生命值。持续<b>6</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+10</b>，手牌<b>+1</b>，法力<b>+1</b>，范围<b>+25%</b>。</p>',
  imelda: '<p>费用<b>0</b>。默认解锁。购买费用<b>10</b>金币。</p><h4>卡牌效果</h4><p>获得<b>18</b>点经验。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出黄色卡牌时，获得<b>1%</b>经验增长。持续<b>5</b>次触发。</p><h4>初始属性</h4><p>法力<b>+1</b>，成长<b>+20%</b>。</p>',
  missingn0: '<p>费用<b>0</b>。通过击败红死神解锁。购买费用<b>6,666</b>金币。</p><h4>卡牌效果</h4><p>增加<b>4</b>点护甲。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出红色卡牌时，抽<b>2</b>张牌。持续<b>170</b>次触发。</p><h4>初始属性</h4><p>恢复<b>+1</b>，手牌<b>+8</b>，法力<b>+80</b>，护甲<b>+125</b>，力量<b>+80%</b>，范围<b>+260%</b>，发射数量<b>+2</b>，磁吸<b>+8</b>，复活<b>+2%</b>，幸运<b>+80%</b>，成长<b>+80%</b>，贪欲<b>+80%</b>，诅咒<b>+95</b>。</p>',
  mortaccio: '<p>费用<b>0</b>。通过击败<b>444</b>个骷髅解锁。</p><h4>卡牌效果</h4><p><em>数量</em>：额外发射<b>2</b>个投射物。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出蓝色卡牌时，额外发射<b>1</b>个投射物。持续<b>7</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+5</b>，恢复<b>+1</b>，手牌<b>+1</b>，发射数量<b>+2</b>。</p>',
  porta: '<p>费用<b>0</b>。通过打出<b>100</b>张<ref id="lightning_ring">闪电戒指</ref>卡牌解锁。</p><h4>卡牌效果</h4><p>投射物命中次数增加<b>50%</b>（<b>11</b>回合持续）。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出红色卡牌时，增加<b>1</b>点法力。</p><h4>初始属性</h4><p>法力<b>+1</b>，范围<b>+40%</b>。</p>',
  krochi: '<p>费用<b>1</b>。通过累计击败<b>6,666</b>个敌人解锁。</p><h4>卡牌效果</h4><p>获得<b>10%</b>复活概率。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出Wild卡牌时，获得<b>5%</b>复活概率。持续<b>10</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+1</b>，复活<b>+100%</b>，放逐<b>+5</b>。</p>',
  lama: '<p>费用<b>1</b>。通过以<b>10%</b>或更高诅咒完成地下城解锁。</p><h4>卡牌效果</h4><p>伤害增加<b>50%</b>。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出蓝色卡牌时，伤害增加<b>15%</b>。持续<b>5</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+10</b>，护甲<b>+5</b>，力量<b>+50%</b>。</p>',
  pugnala: '<p>费用<b>1</b>。通过在狂暴森林中找到棺材解锁。</p><h4>卡牌效果</h4><p><em>力量</em>：伤害增加<b>20%</b>。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出黄色卡牌时，抽<b>1</b>张牌。持续<b>3</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+2</b>，力量<b>+30%</b>。</p>',
  concetta: '<p>费用<b>1</b>。通过在加洛塔中找到棺材解锁。购买费用<b>1,840</b>金币。</p><h4>卡牌效果</h4><p><em>范围</em>：攻击造成<b>10%</b>溅射伤害。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出红色卡牌时，攻击造成<b>5%</b>溅射伤害。持续<b>10</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+1</b>，法力<b>+1</b>，范围<b>+50%</b>。</p>',
  dommario: '<p>费用<b>1</b>。通过收集<b>5,000</b>枚金币解锁。</p><h4>卡牌效果</h4><p><em>持续</em>：爬行者触发更多能力后才离开（+<b>2</b>次）。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出紫色卡牌时，造成<b>40</b>点伤害并有几率击退。持续<b>7</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+1</b>，法力<b>+1</b>。</p>',
  gallo: '<p>费用<b>1</b>。通过在加洛塔中击败加洛解锁。购买费用<b>5,200</b>金币。</p><h4>卡牌效果</h4><p><em>贪欲</em>：金币获取增加<b>25%</b>。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出Wild卡牌时，金币获取增加<b>10%</b>。持续<b>8</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+30</b>，法力<b>+1</b>，发射数量<b>+1</b>，持续<b>+3</b>，幸运<b>+50%</b>，贪欲<b>+50%</b>，重掷<b>+10</b>，跳过<b>+10</b>，放逐<b>+10</b>。</p>',
  gennaro: '<p>费用<b>1</b>。通过在疯狂森林中击败曼提恰纳解锁。购买费用<b>600</b>金币。</p><h4>卡牌效果</h4><p>额外发射<b>2</b>个投射物。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出红色卡牌时，造成<b>90</b>点伤害。持续<b>5</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+1</b>，力量<b>+25%</b>，发射数量<b>+1</b>。</p>',
  giovanna: '<p>费用<b>1</b>。通过在图书馆圣所中找到棺材解锁。</p><h4>卡牌效果</h4><p>增加<b>20%</b>幸运。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出紫色卡牌时，抽<b>1</b>张牌。持续<b>6</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+1</b>，法力<b>+1</b>，幸运<b>+50%</b>，贪欲<b>+25%</b>，重掷<b>+5</b>。</p>',
  pasqualina: '<p>费用<b>1</b>。通过在镶嵌图书馆中使用伊梅尔达达到<b>20</b>级解锁。购买费用<b>1,100</b>金币。</p><h4>卡牌效果</h4><p><em>范围</em>：攻击造成<b>10%</b>溅射伤害。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出紫色卡牌时，手牌上限增加<b>1</b>。持续<b>2</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+5</b>，手牌<b>+1</b>。</p>',
  poe: '<p>费用<b>1</b>。通过打出<b>25</b>张<ref id="garlic">大蒜</ref>卡牌解锁。购买费用<b>500</b>金币。</p><h4>卡牌效果</h4><p><em>范围</em>：攻击造成<b>20%</b>溅射伤害。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出蓝色卡牌时，抽<b>1</b>张牌。持续<b>3</b>次触发。</p><h4>初始属性</h4><p>手牌<b>+1</b>，范围<b>+20%</b>。</p>',
  poppea: '<p>费用<b>1</b>。通过在牛奶工厂中找到棺材解锁。</p><h4>卡牌效果</h4><p>手牌上限增加<b>1</b>。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出黄色卡牌时，爬行者触发更多能力后才离开（+<b>1</b>次）。持续<b>9</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+10</b>，手牌<b>+2</b>，范围<b>+50%</b>，持续<b>+5</b>。</p>',
  osole: '<p>费用<b>1</b>。通过在加洛塔中击败<b>15</b>只龙虾解锁。</p><h4>卡牌效果</h4><p><em>数量</em>：额外发射<b>3</b>个投射物。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出红色卡牌时，增加<b>5%</b>幸运。持续<b>4</b>次触发。</p><h4>初始属性</h4><p>最大生命值<b>+20</b>，发射数量<b>+3</b>。</p>',
  ramba: '<p>费用<b>1</b>。通过在奶制品工厂中击败牛奶元素解锁。</p><h4>卡牌效果</h4><p><em>数量</em>：额外发射<b>3</b>个投射物。<em>爬行者</em>。</p><h4>爬行者能力</h4><p>打出紫色卡牌时，增加<b>1</b>个发射数量。</p><h4>初始属性</h4><p>最大生命值<b>+10</b>，恢复<b>+2</b>，范围<b>+20%</b>，发射数量<b>+2</b>。</p>',
  divano: '<p><em>未使用角色</em>。当前游戏中不可用，但存在配置数据。</p>'
};


// ═══════════════════════════════════════
// 解锁项数据（163项）
// 数据来源：https://vampire.survivors.wiki/w/Crawlers:Unlocks
// ═══════════════════════════════════════
const UNLOCKS = [
  { id: "antonio", name: "安东尼奥", nameEn: "Antonio", category: "角色", image: "images/unlocks/CSprite-Antonio.png", description: "在普通的意大利乡村中救出安东尼奥。", unlocks: "可使用角色：安东尼奥" },
  { id: "combo_stack", name: "连击堆叠", nameEn: "Combo Stack", category: "功能", image: "images/unlocks/CSprite-Combo_Stack.png", description: "在教程中找到这些薄饼。", unlocks: "解锁连击堆叠" },
  { id: "the_inn", name: "旅店", nameEn: "The Inn", category: "功能", image: "images/unlocks/CSprite-The_Inn.png", description: "解锁爬行者选择。", unlocks: "解锁爬行者选择" },
  { id: "gem_hammer", name: "宝石锤", nameEn: "Gem Hammer", category: "遗物", image: "images/unlocks/CSprite-Gem_Hammer.png", description: "找到宝石锤遗物。", unlocks: "解锁宝石镶嵌系统" },
  { id: "hollow_heart", name: "空虚之心", nameEn: "Hollow Heart", category: "物品", image: "images/unlocks/CSprite-Hollow_Heart.png", description: "达到10级。", unlocks: "可使用卡牌：空虚之心" },
  { id: "bloody_tear", name: "血笞", nameEn: "Bloody Tear", category: "进化", image: "images/unlocks/CSprite-Bloody_Tear.png", description: "进化神鞭。", unlocks: "解锁：血笞" },
  { id: "crown", name: "王冠", nameEn: "Crown", category: "物品", image: "images/unlocks/CSprite-Crown.png", description: "达到15级。", unlocks: "可使用卡牌：王冠" },
  { id: "power_ups_shop", name: "强化商店", nameEn: "Power Ups Shop", category: "功能", image: "images/unlocks/CSprite-Power_Ups_Shop.png", description: "收集250枚金币。", unlocks: "解锁强化商店" },
  { id: "inlaid_library", name: "嵌饰图书馆", nameEn: "Inlaid Library", category: "关卡", image: "images/unlocks/CSprite-Inlaid_Library.png", description: "在疯狂森林中达到10级。", unlocks: "解锁关卡：嵌饰图书馆" },
  { id: "guiding_light", name: "引路之光", nameEn: "Guiding Light", category: "遗物", image: "images/unlocks/CSprite-Guiding_Light.png", description: "找到引路之光遗物。", unlocks: "解锁遗物：引路之光" },
  { id: "pasqualina", name: "帕斯姱丽娜", nameEn: "Pasqualina", category: "角色", image: "images/unlocks/CSprite-Pasqualina.png", description: "在镶嵌图书馆中使用伊梅尔达达到20级。", unlocks: "可使用角色：帕斯姱丽娜" },
  { id: "runetracer", name: "痕印石", nameEn: "Runetracer", category: "物品", image: "images/unlocks/CSprite-Runetracer.png", description: "使用帕斯姱丽娜达到10级。", unlocks: "可使用卡牌：痕印石" },
  { id: "no_future", name: "爆裂", nameEn: "No Future", category: "进化", image: "images/unlocks/CSprite-NO_FUTURE.png", description: "进化痕印石。", unlocks: "解锁：爆裂" },
  { id: "spellbinder", name: "咒缚盒", nameEn: "Spellbinder", category: "物品", image: "images/unlocks/CSprite-Spellbinder.png", description: "打出10张痕印石卡牌。", unlocks: "可使用卡牌：咒缚盒" },
  { id: "stone_mask", name: "石面具", nameEn: "Stone Mask", category: "物品", image: "images/unlocks/CSprite-Stone_Mask.png", description: "找到并打出一张石面具。", unlocks: "可使用卡牌：石面具" },
  { id: "furious_forest", name: "狂怒森林", nameEn: "Furious Forest", category: "关卡", image: "images/unlocks/CSprite-Furious_Forest.png", description: "完成疯狂森林。", unlocks: "解锁关卡：狂怒森林" },
  { id: "gennaro", name: "雅那略", nameEn: "Gennaro", category: "角色", image: "images/unlocks/CSprite-Gennaro.png", description: "在疯狂森林中击败曼提恰纳。", unlocks: "可使用角色：雅那略" },
  { id: "bracer", name: "护腕", nameEn: "Bracer", category: "物品", image: "images/unlocks/CSprite-Bracer.png", description: "打出99张国王圣经卡牌。", unlocks: "可使用卡牌：护腕" },
  { id: "thousand_edge", name: "千刃", nameEn: "Thousand Edge", category: "进化", image: "images/unlocks/CSprite-Thousand_Edge.png", description: "进化飞刀。", unlocks: "解锁：千刃" },
  { id: "polent_r", name: "波伦提尔", nameEn: "Polentir", category: "遗物", image: "images/unlocks/CSprite-Polentír.png", description: "找到波伦提尔遗物。", unlocks: "解锁遗物：波伦提尔" },
  { id: "experimental_medicine", name: "实验医药", nameEn: "Experimental Medicine", category: "奥术", image: "images/unlocks/CSprite-Experimental_Medicine.png", description: "获得波伦提尔遗物后解锁。", unlocks: "解锁奥术：实验医药" },
  { id: "shield_bash", name: "盾击", nameEn: "Shield Bash", category: "奥术", image: "images/unlocks/CSprite-Shield_Bash.png", description: "获得波伦提尔遗物后解锁。", unlocks: "解锁奥术：盾击" },
  { id: "relic_museum", name: "遗物博物馆", nameEn: "Relic Museum", category: "功能", image: "images/unlocks/CSprite-Relic_Museum.png", description: "完成两个地下城。", unlocks: "解锁遗物博物馆" },
  { id: "arca", name: "阿卡", nameEn: "Arca", category: "角色", image: "images/unlocks/CSprite-Arca.png", description: "打出100张火焰魔杖卡牌。", unlocks: "可使用角色：阿卡" },
  { id: "fire_wand", name: "火焰魔杖", nameEn: "Fire Wand", category: "物品", image: "images/unlocks/CSprite-Fire_Wand.png", description: "破坏20个光源。", unlocks: "可使用卡牌：火焰魔杖" },
  { id: "hellfire", name: "地狱火", nameEn: "Hellfire", category: "进化", image: "images/unlocks/CSprite-Hellfire.png", description: "进化火焰魔杖。", unlocks: "解锁：地狱火" },
  { id: "mana_syphon", name: "法力虹吸", nameEn: "Mana Syphon", category: "奥术", image: "images/unlocks/CSprite-Mana_Syphon.png", description: "一回合内获得15点法力。", unlocks: "解锁奥术：法力虹吸" },
  { id: "empty_tome", name: "空白之书", nameEn: "Empty Tome", category: "物品", image: "images/unlocks/CSprite-Empty_Tome.png", description: "收集2个法力球。", unlocks: "可使用卡牌：空白之书" },
  { id: "holy_wand", name: "神授魔杖", nameEn: "Holy Wand", category: "进化", image: "images/unlocks/CSprite-Holy_Wand.png", description: "进化强能魔杖。", unlocks: "解锁：神授魔杖" },
  { id: "sharp_mind", name: "敏锐心智", nameEn: "Sharp Mind", category: "奥术", image: "images/unlocks/CSprite-Sharp_Mind.png", description: "打出100张紫色卡牌。", unlocks: "解锁奥术：敏锐心智" },
  { id: "poe", name: "波", nameEn: "Poe", category: "角色", image: "images/unlocks/CSprite-Poe.png", description: "打出25张大蒜卡牌。", unlocks: "可使用角色：波" },
  { id: "pummarola", name: "愈伤番茄", nameEn: "Pummarola", category: "物品", image: "images/unlocks/CSprite-Pummarola.png", description: "使用雅那略达到10级。", unlocks: "可使用卡牌：愈伤番茄" },
  { id: "garlic", name: "大蒜", nameEn: "Garlic", category: "物品", image: "images/unlocks/CSprite-Garlic.png", description: "拾取5个地面鸡腿。", unlocks: "可使用卡牌：大蒜" },
  { id: "soul_eater", name: "噬魂纹章", nameEn: "Soul Eater", category: "进化", image: "images/unlocks/CSprite-Soul_Eater.png", description: "进化大蒜。", unlocks: "解锁：噬魂纹章" },
  { id: "peachone", name: "白鸽", nameEn: "Peachone", category: "物品", image: "images/unlocks/CSprite-Peachone.png", description: "达到25级。", unlocks: "可使用卡牌：白鸽" },
  { id: "ebony_wings", name: "黑翼", nameEn: "Ebony Wings", category: "物品", image: "images/unlocks/CSprite-Ebony_Wings.png", description: "打出1次白鸽卡牌。", unlocks: "可使用卡牌：黑翼" },
  { id: "vandalier", name: "摧锋", nameEn: "Vandalier", category: "进化", image: "images/unlocks/CSprite-Vandalier.png", description: "合体白鸽与黑翼。", unlocks: "解锁：摧锋" },
  { id: "library_west_wing", name: "图书馆西翼", nameEn: "Library West Wing", category: "关卡", image: "images/unlocks/CSprite-Library_West_Wing.png", description: "完成镶嵌图书馆。", unlocks: "解锁关卡：图书馆西翼" },
  { id: "attractorb", name: "念力法球", nameEn: "Attractorb", category: "物品", image: "images/unlocks/CSprite-Attractorb.png", description: "找到并打出1张吸尘器卡牌。", unlocks: "可使用卡牌：念力法球" },
  { id: "grim_grimoire", name: "恐怖魔典", nameEn: "Grim Grimoire", category: "遗物", image: "images/unlocks/CSprite-Grim_Grimoire.png", description: "找到暗黑魔典遗物。", unlocks: "解锁遗物：恐怖魔典" },
  { id: "teeny_bridge", name: "微小桥", nameEn: "Teeny Bridge", category: "关卡", image: "images/unlocks/CSprite-Teeny_Bridge.png", description: "在镶嵌图书馆中达到15级。", unlocks: "解锁关卡：微小桥" },
  { id: "dommario", name: "多马利奥", nameEn: "Dommario", category: "角色", image: "images/unlocks/CSprite-Dommario.png", description: "收集5,000枚金币。", unlocks: "可使用角色：多马利奥" },
  { id: "unholy_vespers", name: "渎神祷书", nameEn: "Unholy Vespers", category: "进化", image: "images/unlocks/CSprite-Unholy_Vespers.png", description: "进化国王圣经。", unlocks: "解锁：渎神祷书" },
  { id: "overkill", name: "超额击杀", nameEn: "Overkill", category: "遗物", image: "images/unlocks/CSprite-Overkill.png", description: "找到过度杀伤遗物。", unlocks: "解锁遗物：超额击杀" },
  { id: "stardust_anvil", name: "星尘铁砧", nameEn: "Stardust Anvil", category: "遗物", image: "images/unlocks/CSprite-Stardust_Anvil.png", description: "找到星尘铁砧遗物。", unlocks: "解锁遗物：星尘铁砧" },
  { id: "lama", name: "拉玛", nameEn: "Lama", category: "角色", image: "images/unlocks/CSprite-Lama.png", description: "以10%或更高诅咒完成一个地下城。", unlocks: "可使用角色：拉玛" },
  { id: "death_spiral", name: "死亡旋风", nameEn: "Death Spiral", category: "进化", image: "images/unlocks/CSprite-Death_Spiral.png", description: "进化斧头。", unlocks: "解锁：死亡旋风" },
  { id: "over_the_top", name: "登峰造极", nameEn: "Over The Top", category: "奥术", image: "images/unlocks/CSprite-Over_The_Top.png", description: "打出100张爬行者卡牌。", unlocks: "解锁奥术：登峰造极" },
  { id: "dairy_plant", name: "奶牛工厂", nameEn: "Dairy Plant", category: "关卡", image: "images/unlocks/CSprite-Dairy_Plant.png", description: "完成小桥。", unlocks: "解锁关卡：奶牛工厂" },
  { id: "ramba", name: "兰巴", nameEn: "Ramba", category: "角色", image: "images/unlocks/CSprite-Ramba.png", description: "击败牛奶元素。", unlocks: "可使用角色：兰巴" },
  { id: "carr_llo", name: "卡雷洛", nameEn: "Carrello", category: "物品", image: "images/unlocks/CSprite-Carréllo.png", description: "破坏5辆矿车。", unlocks: "可使用卡牌：卡雷洛" },
  { id: "porta", name: "珀塔", nameEn: "Porta", category: "角色", image: "images/unlocks/CSprite-Porta.png", description: "打出100张闪电戒指卡牌。", unlocks: "可使用角色：珀塔" },
  { id: "lightning_ring", name: "闪电戒指", nameEn: "Lightning Ring", category: "物品", image: "images/unlocks/CSprite-Lightning_Ring.png", description: "击败2,500个敌人。", unlocks: "可使用卡牌：闪电戒指" },
  { id: "duplicator", name: "双鸾宝镯", nameEn: "Duplicator", category: "物品", image: "images/unlocks/CSprite-Duplicator.png", description: "打出25张强能魔杖卡牌。", unlocks: "可使用卡牌：双鸾宝镯" },
  { id: "thunder_loop", name: "雷环", nameEn: "Thunder Loop", category: "进化", image: "images/unlocks/CSprite-Thunder_Loop.png", description: "进化闪电戒指。", unlocks: "解锁：雷环" },
  { id: "make_a_scene", name: "制造场面", nameEn: "Make A Scene", category: "奥术", image: "images/unlocks/CSprite-Make_a_Scene.png", description: "触发1,500次爬行者能力。", unlocks: "解锁奥术：制造场面" },
  { id: "berserk_wood", name: "狂暴森林", nameEn: "Berserk Wood", category: "关卡", image: "images/unlocks/CSprite-Berserk_Wood.png", description: "完成狂暴森林。", unlocks: "解锁关卡：狂暴森林" },
  { id: "mortaccio", name: "死东西", nameEn: "Mortaccio", category: "角色", image: "images/unlocks/CSprite-Mortaccio.png", description: "击败444个骷髅。", unlocks: "可使用角色：死东西" },
  { id: "bone", name: "骨头", nameEn: "Bone", category: "物品", image: "images/unlocks/CSprite-Bone.png", description: "使用死东西达到5级。", unlocks: "可使用卡牌：骨头" },
  { id: "pugnala", name: "普格纳拉", nameEn: "Pugnala", category: "角色", image: "images/unlocks/CSprite-Pugnala.png", description: "在狂暴森林中找到棺材。", unlocks: "可使用角色：普格纳拉" },
  { id: "tirajisu", name: "提拉吉苏", nameEn: "Tirajisú", category: "物品", image: "images/unlocks/CSprite-Tirajisú.png", description: "使用柯洛奇达到20级。", unlocks: "可使用卡牌：提拉吉苏" },
  { id: "eight_the_sparrow", name: "麻雀小八", nameEn: "Eight The Sparrow", category: "物品", image: "images/unlocks/CSprite-Eight_The_Sparrow.png", description: "使用普格纳拉达到15级。", unlocks: "可使用卡牌：麻雀小八" },
  { id: "phiera_der_tuphello", name: "图菲罗街市", nameEn: "Phiera Der Tuphello", category: "物品", image: "images/unlocks/CSprite-Phiera_Der_Tuphello.png", description: "使用普格纳拉达到20级。", unlocks: "可使用卡牌：图菲罗街市" },
  { id: "phieraggi", name: "菲拉吉", nameEn: "Phieraggi", category: "进化", image: "images/unlocks/CSprite-Phieraggi.png", description: "合体麻雀小八与图菲罗街市。", unlocks: "解锁：菲拉吉" },
  { id: "and_another", name: "再来一个", nameEn: "And Another", category: "奥术", image: "images/unlocks/CSprite-And_Another.png", description: "打出150张免费卡牌。", unlocks: "解锁奥术：再来一个" },
  { id: "library_sanctum", name: "图书馆圣殿", nameEn: "Library Sanctum", category: "关卡", image: "images/unlocks/CSprite-Library_Sanctum.png", description: "完成图书馆西翼。", unlocks: "解锁关卡：图书馆圣殿" },
  { id: "cavallo", name: "熊", nameEn: "Cavallo", category: "角色", image: "images/unlocks/CSprite-Cavallo.png", description: "击败250个狮头。", unlocks: "可使用角色：熊" },
  { id: "cherry_bomb", name: "樱桃炸弹", nameEn: "Cherry Bomb", category: "物品", image: "images/unlocks/CSprite-Cherry_Bomb.png", description: "使用熊达到15级。", unlocks: "可使用卡牌：樱桃炸弹" },
  { id: "giovanna", name: "乔万娜", nameEn: "Giovanna", category: "角色", image: "images/unlocks/CSprite-Giovanna.png", description: "在图书馆圣所中找到棺材。", unlocks: "可使用角色：乔万娜" },
  { id: "gatti_amari", name: "彪悍猫", nameEn: "Gatti Amari", category: "物品", image: "images/unlocks/CSprite-Gatti_Amari.png", description: "使用乔万娜达到15级。", unlocks: "可使用卡牌：彪悍猫" },
  { id: "vicious_hunger", name: "饕恶魔眼", nameEn: "Vicious Hunger", category: "进化", image: "images/unlocks/CSprite-Vicious_Hunger.png", description: "进化彪悍猫。", unlocks: "解锁：饕恶魔眼" },
  { id: "arcana_finder", name: "奥术探测器", nameEn: "Arcana Finder", category: "遗物", image: "images/unlocks/CSprite-Arcana_Finder.png", description: "找到奥术探测器遗物。", unlocks: "解锁奥术查找器" },
  { id: "swollen_fist", name: "膨胀之拳", nameEn: "Swollen Fist", category: "奥术", image: "images/unlocks/CSprite-Swollen_Fist.png", description: "牌组达到40张。", unlocks: "解锁奥术：膨胀之拳" },
  { id: "milk_factory", name: "牛奶工厂", nameEn: "Milk Factory", category: "关卡", image: "images/unlocks/CSprite-Milk_Factory.png", description: "完成奶制品工厂。", unlocks: "解锁关卡：牛奶工厂" },
  { id: "bomba_infernale", name: "地狱炸弹", nameEn: "Bomba Infernale", category: "遗物", image: "images/unlocks/CSprite-Bomba_Infernale.png", description: "找到地狱炸弹遗物。", unlocks: "解锁遗物：地狱炸弹" },
  { id: "krochi", name: "柯洛奇", nameEn: "Krochi", category: "角色", image: "images/unlocks/CSprite-Krochi.png", description: "累计击败6,666个敌人。", unlocks: "可使用角色：柯洛奇" },
  { id: "cross", name: "十字飞镖", nameEn: "Cross", category: "物品", image: "images/unlocks/CSprite-Cross.png", description: "找到并打出一张念珠卡牌。", unlocks: "可使用卡牌：十字飞镖" },
  { id: "clover", name: "四叶草", nameEn: "Clover", category: "物品", image: "images/unlocks/CSprite-Clover.png", description: "找到并打出10张小四叶草卡牌。", unlocks: "可使用卡牌：四叶草" },
  { id: "heaven_sword", name: "天堂之剑", nameEn: "Heaven Sword", category: "进化", image: "images/unlocks/CSprite-Heaven_Sword.png", description: "进化十字飞镖。", unlocks: "解锁：天堂之剑" },
  { id: "your_shield_my_liege", name: "您的盾牌陛下", nameEn: "Your Shield My Liege", category: "奥术", image: "images/unlocks/CSprite-Your_Shield_My_Liege.png", description: "获得2,000点护甲。", unlocks: "解锁奥术：您的盾牌陛下" },
  { id: "weeny_bridge", name: "纤细桥", nameEn: "Weeny Bridge", category: "关卡", image: "images/unlocks/CSprite-Weeny_Bridge.png", description: "在奶制品工厂中达到15级。", unlocks: "解锁关卡：纤细桥" },
  { id: "clerici", name: "克莱里奇", nameEn: "Clerici", category: "角色", image: "images/unlocks/CSprite-Clerici.png", description: "累计回复1,000点生命值。", unlocks: "可使用角色：克莱里奇" },
  { id: "candelabrador", name: "烛台", nameEn: "Candelabrador", category: "物品", image: "images/unlocks/CSprite-Candelabrador.png", description: "打出3张圣徒水卡牌。", unlocks: "可使用卡牌：烛台" },
  { id: "la_borra", name: "圣徒精华", nameEn: "La Borra", category: "进化", image: "images/unlocks/CSprite-La_Borra.png", description: "进化圣徒水。", unlocks: "解锁：圣徒精华" },
  { id: "gallo_tower", name: "加洛塔", nameEn: "Gallo Tower", category: "关卡", image: "images/unlocks/CSprite-Gallo_Tower.png", description: "完成微小桥。", unlocks: "解锁关卡：加洛塔" },
  { id: "lapidary_loupe", name: "宝石放大镜", nameEn: "Lapidary Loupe", category: "遗物", image: "images/unlocks/CSprite-Lapidary_Loupe.png", description: "找到宝石放大镜遗物。", unlocks: "解锁遗物：宝石放大镜" },
  { id: "osole", name: "小太阳", nameEn: "O'Sole", category: "角色", image: "images/unlocks/CSprite-OSole.png", description: "在加洛塔中击败50只龙虾。", unlocks: "可使用角色：小太阳" },
  { id: "celestial_dusting", name: "英华天落", nameEn: "Celestial Dusting", category: "物品", image: "images/unlocks/CSprite-Celestial_Dusting.png", description: "使用O'Sole达到30级。", unlocks: "可使用卡牌：英华天落" },
  { id: "concetta", name: "康雀妲", nameEn: "Concetta", category: "角色", image: "images/unlocks/CSprite-Concetta.png", description: "在加洛塔中找到棺材。", unlocks: "可使用角色：康雀妲" },
  { id: "shadow_pinion", name: "暗影螺钉", nameEn: "Shadow Pinion", category: "物品", image: "images/unlocks/CSprite-Shadow_Pinion.png", description: "使用康雀妲达到15级。", unlocks: "可使用卡牌：暗影螺钉" },
  { id: "wings", name: "翅膀", nameEn: "Wings", category: "物品", image: "images/unlocks/CSprite-Wings.png", description: "达到40级。", unlocks: "可使用卡牌：翅膀" },
  { id: "valkyrie_turner", name: "瓦尔基里喷枪", nameEn: "Valkyrie Turner", category: "进化", image: "images/unlocks/CSprite-Valkyrie_Turner.png", description: "进化暗影螺钉。", unlocks: "解锁：瓦尔基里喷枪" },
  { id: "gallo", name: "加洛", nameEn: "Gallo", category: "角色", image: "images/unlocks/CSprite-Gallo.png", description: "击败加洛。", unlocks: "可使用角色：加洛" },
  { id: "clock_lancet", name: "时钟柳叶刀", nameEn: "Clock Lancet", category: "物品", image: "images/unlocks/CSprite-Clock_Lancet.png", description: "找到并打出一张时钟卡牌。", unlocks: "可使用卡牌：时钟柳叶刀" },
  { id: "christine", name: "克莉丝汀", nameEn: "Christine", category: "角色", image: "images/unlocks/CSprite-Christine.png", description: "找到并打出五芒星卡牌。", unlocks: "可使用角色：克莉丝汀" },
  { id: "pentagram", name: "五芒星", nameEn: "Pentagram", category: "物品", image: "images/unlocks/CSprite-Pentagram.png", description: "达到35级。", unlocks: "可使用卡牌：五芒星" },
  { id: "gorgeous_moon", name: "华月纹章", nameEn: "Gorgeous Moon", category: "进化", image: "images/unlocks/CSprite-Gorgeous_Moon.png", description: "进化五芒星。", unlocks: "解锁：华月纹章" },
  { id: "meany_bridge", name: "刻薄桥", nameEn: "Meany Bridge", category: "关卡", image: "images/unlocks/CSprite-Meany_Bridge.png", description: "在加洛塔中击败巨型敌蟹。", unlocks: "解锁关卡：刻薄桥" },
  { id: "chain_link", name: "连锁链接", nameEn: "Chain Link", category: "奥术", image: "images/unlocks/CSprite-Chain_Link.png", description: "达到12连击或更高。", unlocks: "解锁奥术：连锁链接" },
  { id: "curd_refinery", name: "凝乳精炼厂", nameEn: "Curd Refinery", category: "关卡", image: "images/unlocks/CSprite-Curd_Refinery.png", description: "完成牛奶工厂。", unlocks: "解锁关卡：凝乳精炼厂" },
  { id: "poppea", name: "波佩阿", nameEn: "Poppea", category: "角色", image: "images/unlocks/CSprite-Poppea.png", description: "在牛奶工厂中找到棺材。", unlocks: "可使用角色：波佩阿" },
  { id: "song_of_mana", name: "魔力歌谣", nameEn: "Song of Mana", category: "物品", image: "images/unlocks/CSprite-Song_of_Mana.png", description: "使用波佩阿达到30级。", unlocks: "可使用卡牌：魔力歌谣" },
  { id: "mannajja", name: "黑乐谱", nameEn: "Mannajja", category: "进化", image: "images/unlocks/CSprite-Mannajja.png", description: "进化魔力歌谣。", unlocks: "解锁：黑乐谱" },
  { id: "ultimate_ultra_overkill", name: "终极超额击杀", nameEn: "Ultimate Ultra Overkill", category: "遗物", image: "images/unlocks/CSprite-Ultimate_Ultra_Overkill.png", description: "找到终极超级杀戮遗物。", unlocks: "解锁遗物：终极超额击杀" },
  { id: "capella_magna", name: "卡佩拉大教堂", nameEn: "Capella Magna", category: "关卡", image: "images/unlocks/CSprite-Cappella_Magna.png", description: "完成凶恶桥。", unlocks: "解锁关卡：卡佩拉大教堂" },
  { id: "cappella_ultima", name: "终极礼拜堂", nameEn: "Cappella Ultima", category: "关卡", image: "images/unlocks/CSprite-Cappella_Ultima.png", description: "完成大教堂。", unlocks: "解锁关卡：终极礼拜堂" },
  { id: "friendship_amulet", name: "友谊护符", nameEn: "Friendship Amulet", category: "物品", image: "images/unlocks/CSprite-Friendship_Amulet.png", description: "达到7连击或更高。", unlocks: "可使用卡牌：友谊护符" },
  { id: "parm_aegis", name: "帕尔姆神盾", nameEn: "Parm Aegis", category: "物品", image: "images/unlocks/CSprite-Parm_Aegis.png", description: "达到12连击或更高。", unlocks: "可使用卡牌：帕尔姆神盾" },
  { id: "bracelet", name: "魔环", nameEn: "Bracelet", category: "物品", image: "images/unlocks/CSprite-Bracelet.png", description: "达到15连击或更高。", unlocks: "可使用卡牌：魔环" },
  { id: "ovenkilt", name: "烤炉裙甲", nameEn: "Ovenkilt", category: "遗物", image: "images/unlocks/CSprite-Ovenkilt.png", description: "找到烤炉裙遗物。", unlocks: "解锁遗物：烤炉裙甲" },
  { id: "wild_buff", name: "万能强化", nameEn: "Wild Buff", category: "奥术", image: "images/unlocks/CSprite-Wild_Buff.png", description: "打出200张从光源获得的卡牌。", unlocks: "解锁奥术：万能强化" },
  { id: "nduja", name: "恩杜亚", nameEn: "Nduja", category: "宝石", image: "images/unlocks/CSprite-Nduja.png", description: "击败内苏弗里托。", unlocks: "解锁宝石：恩杜亚宝石" },
  { id: "fireproof", name: "防火", nameEn: "Fireproof", category: "宝石", image: "images/unlocks/CSprite-Fireproof.png", description: "完成凝乳精炼厂。", unlocks: "解锁宝石：防火宝石" },
  { id: "crawler_caller", name: "爬行者召唤", nameEn: "Crawler Caller", category: "宝石", image: "images/unlocks/CSprite-Crawler_Caller.png", description: "完成图书馆圣所。", unlocks: "解锁宝石：探索者召唤宝石" },
  { id: "yin_yang", name: "阴阳", nameEn: "Yin Yang", category: "宝石", image: "images/unlocks/CSprite-Yin_Yang.png", description: "完成狂暴森林。", unlocks: "解锁宝石：阴阳宝石" },
  { id: "mana_rebate", name: "法力回赠", nameEn: "Mana Rebate", category: "宝石", image: "images/unlocks/CSprite-Mana_Rebate.png", description: "一回合内获得15点法力。", unlocks: "解锁宝石：法力回赠宝石" },
  { id: "blue_trigger", name: "蓝色触发", nameEn: "Blue Trigger", category: "宝石", image: "images/unlocks/CSprite-Blue_Trigger.png", description: "打出250张蓝色卡牌。", unlocks: "解锁宝石：蓝色触发条件宝石" },
  { id: "bombard", name: "轰炸", nameEn: "Bombard", category: "宝石", image: "images/unlocks/CSprite-Bombard.png", description: "打出50张樱桃炸弹卡牌。", unlocks: "解锁宝石：轰炸宝石" },
  { id: "growth", name: "成长", nameEn: "Growth", category: "宝石", image: "images/unlocks/CSprite-Growth_(gem).png", description: "打出5张王冠卡牌。", unlocks: "解锁宝石：成长宝石" },
  { id: "calcium", name: "钙质", nameEn: "Calcium", category: "宝石", image: "images/unlocks/CSprite-Calcium.png", description: "打出99张骨头卡牌。", unlocks: "解锁宝石：钙质宝石" },
  { id: "countdown", name: "倒计时", nameEn: "Countdown", category: "宝石", image: "images/unlocks/CSprite-Countdown.png", description: "打出321张空白之书卡牌。", unlocks: "解锁宝石：倒扣宝石" },
  { id: "copy", name: "复制", nameEn: "Copy", category: "宝石", image: "images/unlocks/CSprite-Copy.png", description: "打出1,000张卡牌。", unlocks: "解锁宝石：复制宝石" },
  { id: "decimate", name: "削弱", nameEn: "Decimate", category: "宝石", image: "images/unlocks/CSprite-Decimate.png", description: "造成666,666点伤害。", unlocks: "解锁宝石：削弱宝石" },
  { id: "destroy", name: "销毁", nameEn: "Destroy", category: "宝石", image: "images/unlocks/CSprite-Destroy.png", description: "打出100张从光源获得的卡牌。", unlocks: "解锁宝石：销毁宝石" },
  { id: "easy_combo", name: "轻松连击", nameEn: "Easy Combo", category: "宝石", image: "images/unlocks/CSprite-Easy_Combo.png", description: "达到5连击或更高。", unlocks: "解锁宝石：轻松连击宝石" },
  { id: "drain", name: "吸血", nameEn: "Drain", category: "宝石", image: "images/unlocks/CSprite-Drain.png", description: "累计回复1,500点生命值。", unlocks: "解锁宝石：吸血宝石" },
  { id: "duration", name: "持续时间", nameEn: "Duration", category: "宝石", image: "images/unlocks/CSprite-Duration_(gem).png", description: "打出10张咒缚盒卡牌。", unlocks: "解锁宝石：持续时间宝石" },
  { id: "echo", name: "回响", nameEn: "Echo", category: "宝石", image: "images/unlocks/CSprite-Echo.png", description: "打出3,000张卡牌。", unlocks: "解锁宝石：回响宝石" },
  { id: "free_to_play", name: "免费", nameEn: "Free To Play", category: "宝石", image: "images/unlocks/CSprite-Free_To_Play.png", description: "打出200张免费卡牌。", unlocks: "解锁宝石：免费宝石" },
  { id: "freeze", name: "冰冻", nameEn: "Freeze", category: "宝石", image: "images/unlocks/CSprite-Freeze.png", description: "打出时钟柳叶刀卡牌。", unlocks: "解锁宝石：冰冻宝石" },
  { id: "restore_health", name: "恢复生命", nameEn: "Restore Health", category: "宝石", image: "images/unlocks/CSprite-Restore_Health.png", description: "打出10张愈伤番茄卡牌。", unlocks: "解锁宝石：恢复生命值宝石" },
  { id: "coin_count", name: "金币计数", nameEn: "Coin Count", category: "宝石", image: "images/unlocks/CSprite-Coin_Count.png", description: "收集100,000枚金币。", unlocks: "解锁宝石：金币数宝石" },
  { id: "leader", name: "首领", nameEn: "Leader", category: "宝石", image: "images/unlocks/CSprite-Leader.png", description: "造成100,000点伤害。", unlocks: "解锁宝石：首领宝石" },
  { id: "luck", name: "运气", nameEn: "Luck", category: "宝石", image: "images/unlocks/CSprite-Luck_(gem).png", description: "打出5张四叶草卡牌。", unlocks: "解锁宝石：幸运宝石" },
  { id: "magic_hat", name: "魔法帽", nameEn: "Magic Hat", category: "宝石", image: "images/unlocks/CSprite-Magic_Hat.png", description: "打出77张白鸽卡牌。", unlocks: "解锁宝石：魔法帽宝石" },
  { id: "magnetic", name: "磁力", nameEn: "Magnetic", category: "宝石", image: "images/unlocks/CSprite-Magnetic.png", description: "打出2,000张卡牌。", unlocks: "解锁宝石：磁吸宝石" },
  { id: "increase_mana_cost_1", name: "增加法力消耗", nameEn: "Increase Mana Cost 1", category: "功能", image: "images/unlocks/CSprite-Increase_Mana_Cost_(+1).png", description: "收集10个法力球。", unlocks: "解锁：法力消耗调整 +1/-1" },
  { id: "increase_mana_cost_2", name: "增加法力消耗", nameEn: "Increase Mana Cost 2", category: "功能", image: "images/unlocks/CSprite-Increase_Mana_Cost_(+2).png", description: "收集20个法力球。", unlocks: "解锁：法力消耗调整 +2/-2" },
  { id: "midas", name: "迈达斯", nameEn: "Midas", category: "宝石", image: "images/unlocks/CSprite-Midas.png", description: "收集5,555枚金币。", unlocks: "解锁宝石：迈达斯宝石" },
  { id: "purple_trigger", name: "紫色触发", nameEn: "Purple Trigger", category: "宝石", image: "images/unlocks/CSprite-Purple_Trigger.png", description: "打出250张紫色卡牌。", unlocks: "解锁宝石：紫色触发条件宝石" },
  { id: "rainbow", name: "彩虹", nameEn: "Rainbow", category: "宝石", image: "images/unlocks/CSprite-Rainbow.png", description: "触发500次爬行者能力。", unlocks: "解锁宝石：彩虹宝石" },
  { id: "red_trigger", name: "红色触发", nameEn: "Red Trigger", category: "宝石", image: "images/unlocks/CSprite-Red_Trigger.png", description: "打出500张红色卡牌。", unlocks: "解锁宝石：红色触发条件宝石" },
  { id: "refund", name: "返还", nameEn: "Refund", category: "宝石", image: "images/unlocks/CSprite-Refund.png", description: "一回合内获得10点法力。", unlocks: "解锁宝石：返还宝石" },
  { id: "remote", name: "遥控", nameEn: "Remote", category: "宝石", image: "images/unlocks/CSprite-Remote.png", description: "破坏5辆矿车。", unlocks: "解锁宝石：遥控宝石" },
  { id: "retain", name: "保留", nameEn: "Retain", category: "宝石", image: "images/unlocks/CSprite-Retain.png", description: "手中持有7张卡牌。", unlocks: "解锁宝石：保留宝石" },
  { id: "return", name: "回返", nameEn: "Return", category: "宝石", image: "images/unlocks/CSprite-Return.png", description: "打出300张卡牌。", unlocks: "解锁宝石：返回宝石" },
  { id: "reverse_combo", name: "逆向连击", nameEn: "Reverse Combo", category: "宝石", image: "images/unlocks/CSprite-Reverse_Combo.png", description: "达到6连击或更高。", unlocks: "解锁宝石：逆向连击宝石" },
  { id: "kill_count", name: "击杀计数", nameEn: "Kill Count", category: "宝石", image: "images/unlocks/CSprite-Kill_Count.png", description: "累计击败10,000个敌人。", unlocks: "解锁宝石：击杀数宝石" },
  { id: "armor_strike", name: "护甲打击", nameEn: "Armor Strike", category: "宝石", image: "images/unlocks/CSprite-Armor_Strike.png", description: "一回合内获得15点护甲。", unlocks: "解锁宝石：护甲攻击宝石" },
  { id: "recycle", name: "回收", nameEn: "Recycle", category: "宝石", image: "images/unlocks/CSprite-Recycle.png", description: "手中持有8张卡牌。", unlocks: "解锁宝石：回收宝石" },
  { id: "mug", name: "悬赏", nameEn: "Mug", category: "宝石", image: "images/unlocks/CSprite-Mug.png", description: "收集3,333枚金币。", unlocks: "解锁宝石：悬赏宝石" },
  { id: "quick_draw", name: "快抽", nameEn: "Quick Draw", category: "宝石", image: "images/unlocks/CSprite-Quick_Draw.png", description: "牌组达到30张。", unlocks: "解锁宝石：快抽宝石" },
  { id: "coin_card", name: "金币卡", nameEn: "Coin Card", category: "宝石", image: "images/unlocks/CSprite-Coin_Card.png", description: "找到并打出20张大钱袋卡牌。", unlocks: "解锁宝石：金币卡牌宝石" },
  { id: "triple_damage", name: "三倍伤害", nameEn: "Triple Damage", category: "宝石", image: "images/unlocks/CSprite-Triple_Damage.png", description: "造成500,000点伤害。", unlocks: "解锁宝石：三倍伤害宝石" },
  { id: "uncrackable", name: "坚不可摧", nameEn: "Uncrackable", category: "宝石", image: "images/unlocks/CSprite-Uncrackable.png", description: "击败诡术师。", unlocks: "解锁宝石：坚不可摧宝石" },
  { id: "wild", name: "万能", nameEn: "Wild", category: "宝石", image: "images/unlocks/CSprite-Wild.png", description: "打出100张Wild卡牌。", unlocks: "解锁宝石：万能宝石" },
  { id: "x_mana", name: "X法力", nameEn: "X Mana", category: "宝石", image: "images/unlocks/CSprite-X_Mana.png", description: "打出3,000张紫色卡牌。", unlocks: "解锁宝石：X法力宝石" },
  { id: "mild", name: "温和", nameEn: "Mild", category: "宝石", image: "images/unlocks/CSprite-Mild.png", description: "使用加洛完成加洛塔。", unlocks: "解锁宝石：温和宝石" },
  { id: "yellow_trigger", name: "黄色触发", nameEn: "Yellow Trigger", category: "宝石", image: "images/unlocks/CSprite-Yellow_Trigger.png", description: "打出250张黄色卡牌。", unlocks: "解锁宝石：黄色触发条件宝石" },
  { id: "greed", name: "贪欲", nameEn: "Greed", category: "宝石", image: "images/unlocks/CSprite-Greed_(gem).png", description: "打出10张石面具卡牌。", unlocks: "解锁宝石：贪婪宝石" },
  { id: "skull_o_maniac", name: "疯狂骷髅", nameEn: "Skull O'Maniac", category: "物品", image: "images/unlocks/CSprite-Skull_OManiac.png", description: "使用拉玛达到30级。", unlocks: "可使用卡牌：疯狂骷髅" },
  { id: "sorceress_tears", name: "女巫之泪", nameEn: "Sorceress' Tears", category: "遗物", image: "images/unlocks/CSprite-Sorceress_Tears.png", description: "找到女巫之泪遗物。", unlocks: "解锁遗物：女巫之泪" },
  { id: "jesters_hat", name: "小丑帽", nameEn: "Jester's Hat", category: "奥术", image: "images/unlocks/CSprite-Jesters_Hat.png", description: "打出150张Wild卡牌。", unlocks: "解锁奥术：小丑帽" }
];;


const UNLOCK_PINYIN_MAP = {
  and_another: 'zlyg',
  antonio: 'adna',
  arca: 'ak',
  arcana_finder: 'astcq',
  armor_strike: 'hjdj',
  attractorb: 'nlfq',
  berserk_wood: 'kbsl',
  bloody_tear: 'xc',
  blue_trigger: 'lscf',
  bomba_infernale: 'dyzd',
  bombard: 'hz',
  bone: 'gt',
  bracelet: 'mh',
  bracer: 'hw',
  calcium: 'gz',
  candelabrador: 'zt',
  capella_magna: 'kpldjt',
  cappella_ultima: 'zjlbt',
  carr_llo: 'kll',
  cavallo: 'x',
  celestial_dusting: 'yhtl',
  chain_link: 'lslj',
  cherry_bomb: 'ytzd',
  christine: 'klst',
  clerici: 'kllq',
  clock_lancet: 'szlyd',
  clover: 'syc',
  coin_card: 'jbk',
  coin_count: 'jbjs',
  combo_stack: 'ljdd',
  concetta: 'kqd',
  copy: 'fz',
  countdown: 'djs',
  crawler_caller: 'pxzzh',
  cross: 'szfb',
  crown: 'wg',
  curd_refinery: 'nrjlc',
  dairy_plant: 'nngc',
  death_spiral: 'swxf',
  decimate: 'xr',
  destroy: 'xh',
  dommario: 'dmla',
  drain: 'xx',
  duplicator: 'slbz',
  duration: 'cxsj',
  easy_combo: 'qslj',
  ebony_wings: 'hy',
  echo: 'hx',
  eight_the_sparrow: 'mqxb',
  empty_tome: 'kbzs',
  experimental_medicine: 'syyy',
  fire_wand: 'hymz',
  fireproof: 'fh',
  free_to_play: 'mf',
  freeze: 'bd',
  friendship_amulet: 'yyhf',
  furious_forest: 'knsl',
  gallo: 'jl',
  gallo_tower: 'jlt',
  garlic: 'ds',
  gatti_amari: 'bhm',
  gem_hammer: 'bsc',
  gennaro: 'ynl',
  giovanna: 'qwn',
  gorgeous_moon: 'hywz',
  greed: 'ty',
  grim_grimoire: 'kbmd',
  growth: 'cc',
  guiding_light: 'ylzg',
  heaven_sword: 'ttzj',
  hellfire: 'dyh',
  hollow_heart: 'kxzx',
  holy_wand: 'ssmz',
  increase_mana_cost_1: 'zjflxh',
  increase_mana_cost_2: 'zjflxh',
  inlaid_library: 'qstsg',
  jesters_hat: 'xcm',
  kill_count: 'jsjs',
  krochi: 'klq',
  la_borra: 'stjh',
  lama: 'lm',
  lapidary_loupe: 'bsfdj',
  leader: 'sl',
  library_sanctum: 'tsgsd',
  library_west_wing: 'tsgxy',
  lightning_ring: 'sdjz',
  luck: 'yq',
  magic_hat: 'mfm',
  magnetic: 'cl',
  make_a_scene: 'zzcm',
  mana_rebate: 'flhz',
  mana_syphon: 'flhx',
  mannajja: 'hlp',
  meany_bridge: 'kbq',
  midas: 'mds',
  mild: 'wh',
  milk_factory: 'nngc',
  mortaccio: 'sdx',
  mug: 'xs',
  nduja: 'edy',
  no_future: 'bl',
  osole: 'xty',
  ovenkilt: 'klqj',
  over_the_top: 'dfzj',
  overkill: 'cejs',
  parm_aegis: 'pemsd',
  pasqualina: 'pskln',
  peachone: 'bg',
  pentagram: 'wmx',
  phiera_der_tuphello: 'tfljs',
  phieraggi: 'flj',
  poe: 'b',
  polent_r: 'blte',
  poppea: 'bpa',
  porta: 'pt',
  power_ups_shop: 'qhsd',
  pugnala: 'pgnl',
  pummarola: 'ysfq',
  purple_trigger: 'zscf',
  quick_draw: 'kc',
  rainbow: 'ch',
  ramba: 'lb',
  recycle: 'hs',
  red_trigger: 'hscf',
  refund: 'fh',
  relic_museum: 'ywbwg',
  remote: 'yk',
  restore_health: 'hfsm',
  retain: 'bl',
  return: 'hf',
  reverse_combo: 'nxlj',
  runetracer: 'hys',
  shadow_pinion: 'ayld',
  sharp_mind: 'mrxz',
  shield_bash: 'dj',
  skull_o_maniac: 'fkkl',
  song_of_mana: 'mlgy',
  sorceress_tears: 'nwzl',
  soul_eater: 'shwz',
  spellbinder: 'zfh',
  stardust_anvil: 'xctz',
  stone_mask: 'smj',
  swollen_fist: 'pzzq',
  teeny_bridge: 'wxq',
  the_inn: 'ld',
  thousand_edge: 'qr',
  thunder_loop: 'lh',
  tirajisu: 'tljs',
  triple_damage: 'sbsh',
  ultimate_ultra_overkill: 'zjcejs',
  uncrackable: 'jbkc',
  unholy_vespers: 'dsds',
  valkyrie_turner: 'wejlpq',
  vandalier: 'cf',
  vicious_hunger: 'temy',
  weeny_bridge: 'xxq',
  wild: 'wn',
  wild_buff: 'wnqh',
  wings: 'cb',
  x_mana: 'fl',
  yellow_trigger: 'hscf',
  yin_yang: 'yy',
  your_shield_my_liege: 'nddpbx'
};


// ═══════════════════════════════════════
// 宝石数据（58项）
// 数据来源：https://vampire.survivors.wiki/w/Crawlers:Gems
// ═══════════════════════════════════════
const GEMS = [
  { id: 'amount', name: '发射数量', rarity: 'Rare', image: 'images/unlocks/CSprite-Amount.png', effect: '增加发射数量属性。' },
  { id: 'area', name: '攻击范围', rarity: 'Common', image: 'images/unlocks/CSprite-Area.png', effect: '增加攻击范围属性。' },
  { id: 'armor', name: '防御', rarity: 'Common', image: 'images/unlocks/CSprite-Armor.png', effect: '增加护甲。' },
  { id: 'armor_strike', name: '护甲攻击', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Armor_Strike.png', effect: '打出时将当前护甲值作为伤害。' },
  { id: 'blue_trigger', name: '蓝色触发条件', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Blue_Trigger.png', effect: '添加蓝色触发条件。' },
  { id: 'bombard', name: '轰炸', rarity: 'Rare', image: 'images/unlocks/CSprite-Bombard.png', effect: '樱桃炸弹连击。' },
  { id: 'calcium', name: '钙质', rarity: 'Rare', image: 'images/unlocks/CSprite-Calcium.png', effect: '造成骨头伤害。' },
  { id: 'coin_card', name: '金币卡牌', rarity: 'Rare', image: 'images/unlocks/CSprite-Coin_Card.png', effect: '生成金币卡牌。' },
  { id: 'coin_count', name: '金币数', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Coin_Count.png', effect: '根据当前持有金币数量造成伤害。' },
  { id: 'copy', name: '复制', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Copy.png', effect: '打出时复制一张相同的卡牌。' },
  { id: 'countdown', name: '倒扣', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Countdown.png', effect: '未使用时法力消耗逐渐降低。' },
  { id: 'crawler_caller', name: '探索者召唤', rarity: 'Rare', image: 'images/unlocks/CSprite-Crawler_Caller.png', effect: '将所有爬行者卡牌加入手牌。' },
  { id: 'decimate', name: '削弱', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Decimate.png', effect: '造成敌人10%生命值的伤害。' },
  { id: 'destroy', name: '销毁', rarity: 'Rare', image: 'images/unlocks/CSprite-Destroy.png', effect: '卡牌燃烧销毁，但获得金币。' },
  { id: 'double_damage', name: '双倍伤害', rarity: 'Common', image: 'images/unlocks/CSprite-Double_Damage.png', effect: '造成双倍伤害。' },
  { id: 'drain', name: '吸血', rarity: 'Rare', image: 'images/unlocks/CSprite-Drain.png', effect: '卡牌击杀敌人时回复生命值。' },
  { id: 'draw', name: '抽牌', rarity: 'Rare', image: 'images/unlocks/CSprite-Draw.png', effect: '打出时抽一张牌。' },
  { id: 'duration_gem', name: '持续时间', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Duration_(gem).png', effect: '增加持续时间属性。' },
  { id: 'easy_combo', name: '轻松连击', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Easy_Combo.png', effect: '该卡牌始终享受连击加成。' },
  { id: 'echo', name: '回响', rarity: 'Rare', image: 'images/unlocks/CSprite-Echo.png', effect: '重新触发上一张打出的卡牌效果。' },
  { id: 'evolution', name: '进化', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Evolution.png', effect: '将卡牌进化为更强的武器。' },
  { id: 'fireproof', name: '防火', rarity: 'Rare', image: 'images/unlocks/CSprite-Fireproof.png', effect: '移除卡牌的销毁效果。' },
  { id: 'free_to_play', name: '免费', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Free_To_Play.png', effect: '打出时不消耗任何法力。' },
  { id: 'freeze', name: '冰冻', rarity: 'Rare', image: 'images/unlocks/CSprite-Freeze.png', effect: '冻结一个随机敌人。' },
  { id: 'greed_gem', name: '贪欲', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Greed_(gem).png', effect: '增加贪欲属性。' },
  { id: 'growth_gem', name: '成长', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Growth_(gem).png', effect: '增加成长属性。' },
  { id: 'increase_mana_cost_1', name: '增加法力消耗', rarity: 'Common', image: 'images/unlocks/CSprite-Increase_Mana_Cost_(+1).png', effect: '法力消耗增加1点。' },
  { id: 'increase_mana_cost_2', name: '增加法力消耗', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Increase_Mana_Cost_(+2).png', effect: '法力消耗增加2点。' },
  { id: 'kill_count', name: '击杀数', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Kill_Count.png', effect: '对随机敌人造成当前累计击杀总数的伤害。' },
  { id: 'leader', name: '首领', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Leader.png', effect: '该卡牌在手中时，所有攻击造成额外伤害。' },
  { id: 'luck_gem', name: '运气', rarity: 'Common', image: 'images/unlocks/CSprite-Luck_(gem).png', effect: '增加运气属性。' },
  { id: 'magic_hat', name: '魔法帽', rarity: 'Rare', image: 'images/unlocks/CSprite-Magic_Hat.png', effect: '从上方召唤一只鸽子攻击。' },
  { id: 'magnetic', name: '磁吸', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Magnetic.png', effect: '打出时若牌组中有同名牌，额外抽一张。' },
  { id: 'mana_rebate', name: '法力回赠', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Mana_Rebate.png', effect: '若打出后法力将降至0，改为获得双倍法力。' },
  { id: 'midas', name: '迈达斯', rarity: 'Very Rare', image: 'images/unlocks/CSprite-Midas.png', effect: '该卡牌在手中时，打出其他卡牌可获得金币。' },
  { id: 'might', name: '力量', rarity: 'Common', image: 'images/unlocks/CSprite-Might.png', effect: '增加力量属性。' },
  { id: 'mild', name: '温和', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Mild.png', effect: '永远不会离开手牌，但总会中断连击。' },
  { id: 'mug', name: '悬赏', rarity: 'Common', image: 'images/unlocks/CSprite-Mug.png', effect: '卡牌击杀敌人时获得金币。' },
  { id: 'nduja', name: '恩杜亚', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Nduja.png', effect: '造成辣味伤害。' },
  { id: 'purple_trigger', name: '紫色触发条件', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Purple_Trigger.png', effect: '添加紫色触发条件。' },
  { id: 'quick_draw', name: '快抽', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Quick_Draw.png', effect: '战斗开始时优先抽到此卡牌。' },
  { id: 'rainbow', name: '彩虹', rarity: 'Rare', image: 'images/unlocks/CSprite-Rainbow.png', effect: '添加所有颜色触发条件。' },
  { id: 'recycle', name: '回收', rarity: 'Rare', image: 'images/unlocks/CSprite-Recycle.png', effect: '打出后跳过弃牌堆，直接回到牌组。' },
  { id: 'red_trigger', name: '红色触发条件', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Red_Trigger.png', effect: '添加红色触发条件。' },
  { id: 'reduce_mana_cost_1', name: '减少法力消耗', rarity: 'Common', image: 'images/unlocks/CSprite-Reduce_Mana_Cost_-1.png', effect: '法力消耗减少1点。' },
  { id: 'reduce_mana_cost_2', name: '减少法力消耗', rarity: 'Rare', image: 'images/unlocks/CSprite-Reduce_Mana_Cost_-2.png', effect: '法力消耗减少2点。' },
  { id: 'refund', name: '返还', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Refund.png', effect: '打出时返还消耗的法力。' },
  { id: 'remote', name: '遥控', rarity: 'Rare', image: 'images/unlocks/CSprite-Remote.png', effect: '召唤一辆矿车。' },
  { id: 'restore_health', name: '恢复生命值', rarity: 'Common', image: 'images/unlocks/CSprite-Restore_Health.png', effect: '战斗后恢复生命值。' },
  { id: 'retain', name: '保留', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Retain.png', effect: '抽到时留在手中直到主动使用。' },
  { id: 'return', name: '返回', rarity: 'Rare', image: 'images/unlocks/CSprite-Return.png', effect: '打出后返回手牌。' },
  { id: 'reverse_combo', name: '逆向连击', rarity: 'Rare', image: 'images/unlocks/CSprite-Reverse_Combo.png', effect: '下一张牌可向上或向下延续连击。' },
  { id: 'triple_damage', name: '三倍伤害', rarity: 'Rare', image: 'images/unlocks/CSprite-Triple_Damage.png', effect: '造成三倍伤害。' },
  { id: 'uncrackable', name: '坚不可摧', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Uncrackable.png', effect: '卡牌更不容易破碎。' },
  { id: 'wild', name: '万能', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-Wild.png', effect: '使卡牌变为万能牌。' },
  { id: 'x_mana', name: 'X法力', rarity: 'Ultra Rare', image: 'images/unlocks/CSprite-X_Mana.png', effect: '消耗等于当前剩余法力值。' },
  { id: 'yellow_trigger', name: '黄色触发条件', rarity: 'Uncommon', image: 'images/unlocks/CSprite-Yellow_Trigger.png', effect: '添加黄色触发条件。' },
  { id: 'yin_yang', name: '阴阳', rarity: 'Rare', image: 'images/unlocks/CSprite-Yin_Yang.png', effect: '偶数法力时获得1点法力，奇数法力时抽1张牌。' }
];


const GEM_PINYIN_MAP = {
  amount: "fssl", area: "gjfw", armor: "fy", armor_strike: "hjgj",
  blue_trigger: "lscftj", bombard: "hz", calcium: "gz",
  coin_card: "jbkp", coin_count: "jbs", copy: "fz",
  countdown: "dk", crawler_caller: "tszhs", decimate: "xr",
  destroy: "xh", double_damage: "sbsh", drain: "xx", draw: "cp",
  duration_gem: "cxsj", easy_combo: "qslj", echo: "hx",
  evolution: "jh", fireproof: "fh", free_to_play: "mf",
  freeze: "bd", greed_gem: "ty", growth_gem: "cz",
  increase_mana_cost_1: "zjflxh", increase_mana_cost_2: "zjflxh",
  kill_count: "jss", leader: "sz", luck_gem: "yq",
  magic_hat: "mfm", magnetic: "cx", mana_rebate: "flhs",
  midas: "mds", might: "ll", mild: "wr", mug: "xs", nduja: "ndy",
  purple_trigger: "zscftj", quick_draw: "kc", rainbow: "ch",
  recycle: "hs", red_trigger: "hscftj",
  reduce_mana_cost_1: "jsflxh", reduce_mana_cost_2: "jsflxh",
  refund: "fh", remote: "yk", restore_health: "hfsml",
  retain: "bl", return: "fh", reverse_combo: "nxlj",
  triple_damage: "sbsh", uncrackable: "jbkc", wild: "wn",
  x_mana: "xfl", yellow_trigger: "hscftj", yin_yang: "yy"
};
